### ISSUE TITLE
Got an error when running command docker-compose pull on Ubuntu 18.10

### ISSUE THREAD

**Issue by pettineh** [eclipse-arrowhead/core-java-spring#101]
Version 4.1.3, master branch.

Got an error when running command **docker-compose pull** on Ubuntu, inside the docker directory. The MySQL image gets downloaded just fine but every AH core system produces the same error message: 

`ERROR: for <core-system-name-here> error parsing HTTP 404 response body: invalid character '<' looking for beginning of value: "<html>\r\n<head><title>404 Not Found</title></head>\r\n<body>\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n"
`

Regards
Henri Pettinen

**Comment by tsvetlin** [comment]
Hello!

I'm migrating the image repository to its final location. When it will be available again, I'll update the issue.

Best wishes,
Svetlin

**Comment by tsvetlin** [comment]
Hello!

I've migrated the Image Repository to it's final location, the docker-compose file have been updated . It now also initialises the MySQL Database. 

Please pull the master branch again and go through the Docker install steps.

Best wishes,
Svetlin
