### ISSUE TITLE
What is this five-part AHF naming structure?

### ISSUE THREAD

**Issue by emanuelpalm** [eclipse-arrowhead/core-java-spring#108]
https://github.com/arrowhead-f/core-java-spring/blob/fe050363c4de608ac0c4a3892b70bfa7c3338a08/core-common/src/main/java/eu/arrowhead/common/ApplicationInitListener.java#L173-L176

When experimenting with creating my own AHF producer system (a.k.a. provider), I stumbled upon the `AuthException` shown above. It was trivial for me to update the CN name to such with five parts, where the two last ones are "arrowhead.eu". However, I'm not quite familiar with this five part structure scheme. Could you make the error message better reflect where information about this structure is available?

The only naming conventions for Arrowhead I'm familiar with are listed in this paper:
http://www.diva-portal.org/smash/get/diva2:1315252/FULLTEXT01.pdf

I'm not all-knowing, however. Please share what you know about this naming structure you mention.

**Comment by rbocsi** [comment]
The naming of Arrowhead Systems is not changed in 4.1.3. 

For a system the CN has five parts:
1. system name (e.g. authorization) - you must use the same name when you add your system to the Local Arrowhead Cloud
2. cloud name (e.g. testcloud2)
3. operator name (e.g. aitia) - the name of the organization who maintains the cloud
4. arrowhead
5. eu

The last two are always the same.

For a cloud the CN has 4 parts (2, 3, 4, 5 from the previous list).

We are working on some documentation about certificates and .p12 files. In the mean time you can check the existing .p12 files (of the core systems) for details. 

There is a GUI tool you can use for that: KeyStore Explorer (https://keystore-explorer.org/downloads.html), it is available for all common operation systems.

**Comment by emanuelpalm** [comment]
@rbocsi Is there a paper or other AHF document where this naming convention is specified?

Anyhow. Thank you for explaining the details. Could you not update the error message to communicate this structure? Such as specifying that it must conform to the form `"<system>.<cloud>.<operator>.arrowhead.eu"`?

**Comment by jenseliasson** [comment]
Could you comment on the service naming approach as well?

**Comment by borditamas** [comment]
Hello,
we are going to release the Certificate chapter soon. At the moment it is under review, but you can already check [here](https://github.com/arrowhead-f/core-java-spring/tree/documentation#certificates) and will find the answer you need.

**Comment by borditamas** [comment]
Sorry, just realized that you asked for service naming, and not for the certificates :)
The only naming restriction what the framework is validating, that your service definition cannot be equals to any of the AH Core System Service Definitions.
Service definitions are trimmed (leading and trailing whitespace omitted) and lowercased before saving them into the database.

Current AH Core System Service Definitions
'1', 'gw-public-key'
'2', 'gw-connect-provider'
'3', 'gw-connect-consumer'
'4', 'global-service-discovery'
'5', 'inter-cloud-negotiations',
'6', 'authorization-control-intra'
'7', 'authorization-control-inter'
'8', 'token-generation'
'9', 'auth-public-key'
'10', 'authorization-control-subscription'
'11', 'orchestration-service'
