### ISSUE TITLE
Swagger UI doesn't work or pinging https://<IP>:<port> doesn't work 

### ISSUE THREAD

**Issue by sumi0910** [eclipse-arrowhead/core-java-spring#113]
I have installed 4.1.2 version of the framework but as per my knowledge, it is migrated to 4.1.3 version hence the 4.1.3 snapshot gets created running the command mvn install. Doing netstat - l gives the odd numbering of ports indicating secured mode. 
![image](https://user-images.githubusercontent.com/44111991/66903448-cb204000-f002-11e9-990e-21db9bcb83d2.png)
Things tried:
1.running start_insecure_coresystems.sh (still the framework starts in secure mode)
2.https://github.com/arrowhead-f/core-java/wiki/Creating-Application-System-Certificates 
referred the above link and but couldn't find the script and also tried key-explorer but in vain.

Can you please let me know what can be done further to invoke SwaggerUI. Thanks in advance

**Comment by borditamas** [comment]
Hi Sumi,
4.1.2 is not migrated to 4.1.3.
Use the 4.1.2 release what Svetlin suggested in your former
[issue#92](https://github.com/arrowhead-f/core-java-spring/issues/92). 
Note, that in 4.1.2 the Swagger is available by "/api" path.
