### ISSUE TITLE
How to authorize subscriber to receive payload from publisher

### ISSUE THREAD

**Issue by Msegun** [eclipse-arrowhead/core-java-spring#128]
Hello

We're running coresystems in inseucure mode.
To run coresystems we use the script "start_coresystems_local.sh"

We subscribed our system to a certain event.
`
{
            "eventType": event,
            "subscriberSystem": {
                "systemName": system_name,
                "address": address,
                "port": port
            },
            "sources": [],
            "filterMetadata": {},
            "notifyUri": "/",
            "matchMetadata": False
        }
`
When we publish a message our system does not receive it.

In event_handler documentation we read that subscriber needs to have a valid authorization record in order to receive the message.
Is the authorization record created somehow automatically or do i have to post manually it by authorization swagger?

**Comment by MaGaMeGa** [comment]
Hello Msegun,
You have to post it manually by authorization swagger.

To find out the consumer id (your subscriber' id ) and the provider id (your publisher's id)  use the service registry's swagger. Interface id and service Definition id is irrelevant int the subscriber-publisher case but still has to be valid. In real applications most likely the publisher is also a provider with some registered services on some interface. If it is not so, in your case, you can use any, already registered service id and interface id.
The message should look similar to this one : 
`{ "consumerId": 1, "providerIds": [ 2 ], "interfaceIds": [ 1 ], "serviceDefinitionIds": [ 1 ] }`

**Comment by Msegun** [comment]
Yup thanks that worked. We successfully received a message in our system. Thanks :D
