### ISSUE TITLE
Cannot change name of mysql container in Docker image

### ISSUE THREAD

**Issue by emanuelpalm** [eclipse-arrowhead/core-java-spring#133]
https://github.com/arrowhead-f/core-java-spring/blob/bdf3257a35c4ce7651d830ab7f1478c33731f895/docker/docker-compose.yml#L5

If I change the above name in the docker-compose file and all the system configuration files in the `core_system_config/` folder, the Docker images will keep trying to connect to `https://compose_mysql_1` rather than the new name I use. I guess this could be an issue of an internal configuration file being read instead of an external one.

To be very precise, this is the entry I'm changing in every configuration file:

https://github.com/arrowhead-f/core-java-spring/blob/bdf3257a35c4ce7651d830ab7f1478c33731f895/docker/core_system_config/authorization.properties#L7

The name I'm trying to use is `excloud1_mysql`, but that should matter little. Concretely, I'm trying to bring up two local clouds using `docker-compose`, which I then intend to make communicate via the gatekeeper/gateway systems.

**Comment by emanuelpalm** [comment]
I'm not building the Docker images from scratch, but use the ones you reference in the `docker-compose.yml` file I reference above.

**Comment by tsvetlin** [comment]
Hello!

You can change the name of the MySQL containers, it will work, probably the logging will give you exceptions, what you will see in the docker logs. There may be a bug, something uses the internal configuration file instead of the external. It will be fixed in the future.

**Comment by tsvetlin** [comment]
Hello!

Yesterday I've solved the issue. I'll update the Docker Containers this week.

Best wishes,
Svetlin

**Comment by tsvetlin** [comment]
Hey!

Please pull the containers again ;)

**Comment by emanuelpalm** [comment]
I can confirm that it works as intended now. However, I had to replace the "server.address" field with "domain.name" in all properties files.
