### ISSUE TITLE
How to add certificates to browsers - guide

### ISSUE THREAD

**Issue by tsvetlin** [eclipse-arrowhead/core-java-spring#136]
We should create step by step tutorials with screenshots, how to import the sysop.p12 certificate into the browser. (Chrome and Mozilla)

Mac and Linux - Svetlin
Windows - Gabor / Tamas

**Comment by borditamas** [comment]
Tutorial for win10 is pushed into documentation branch.
https://github.com/arrowhead-f/core-java-spring/blob/documentation/README.md#system-operator-certificate

**Comment by sumi0910** [comment]
Do we have a tutorial for adding certificated in Linux

**Comment by tsvetlin** [comment]
Hello! It's a work in progress. Until you can Google it, you will find many similar guides which will be available also here. On Linux try using Chrome, it works best.

Best wishes,
Svetlin

**Comment by tsvetlin** [comment]
Tutorial for Linux and Mac is available on the link provided by @borditamas
