### ISSUE TITLE
Sequence diagrams for Client Endpoints

### ISSUE THREAD

**Issue by tsvetlin** [eclipse-arrowhead/core-java-spring#137]
Adding sequence diagrams for all Client endpoints would be a great addition to the documentation.
Suggested by: @vanDeventer

**Comment by borditamas** [comment]
Below listed activity diagrams have been pushed into documentation branch. (Activity uml is better in visualization of IF-ELSE statements)

[POST /serviceregistry/query](https://github.com/arrowhead-f/core-java-spring/blob/documentation/README.md#query-activity-diagram)
[POST /serviceregistry/register](https://github.com/arrowhead-f/core-java-spring/blob/documentation/README.md#register-activity-diagram)
[DELETE /serviceregistry/unregister](https://github.com/arrowhead-f/core-java-spring/blob/documentation/README.md#unregister-activity-diagram)
[POST /orchestrator/orchestration](https://github.com/arrowhead-f/core-java-spring/blob/documentation/README.md#orchestration-activity-diagram)
[GET /orchestrator/orchestration/{id}](https://github.com/arrowhead-f/core-java-spring/blob/documentation/README.md#store-orchestration-activity-diagram)
