### ISSUE TITLE
docker container issue

### ISSUE THREAD

**Issue by Towfiqomi** [eclipse-arrowhead/core-java-spring#150]
The containers were working perfectly. Now I am suddenly getting these errors,

com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'coreSystemRegistrationProperties': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'domain.name' in value "${domain.name}"

**Comment by Towfiqomi** [comment]
Have no idea but adding these properties in core systems config files it started working,
domain.name=0.0.0.0
domain.port=8443

**Comment by borditamas** [comment]
Hello,

yes this is a new feature required for hosting purposes. But not yet merged into the master branch. Which branch did you check out?

**Comment by Towfiqomi** [comment]
Hi,

Using the master branch

origin  https://github.com/arrowhead-f/core-java-spring.git (fetch)
origin  https://github.com/arrowhead-f/core-java-spring.git (push)

and Arrowhead instance is running on docker containers,

CONTAINER ID        IMAGE                                                              COMMAND                  CREATED             STATUS              PORTS                                             NAMES
dec27a497b26        portus.arrowhead-ci.tmit.bme.hu/arrowhead/gatekeeper:latest        "/bin/sh -c 'cd /gat…"   30 hours ago        Up 30 hours         0.0.0.0:8449->8449/tcp, 0.0.0.0:38449->8449/tcp   gatekeeper
c6da49e9fceb        portus.arrowhead-ci.tmit.bme.hu/arrowhead/gateway:latest           "/bin/sh -c 'cd /gat…"   30 hours ago        Up 30 hours         0.0.0.0:8453->8453/tcp, 0.0.0.0:38453->8453/tcp   gateway
18201dbe6549        portus.arrowhead-ci.tmit.bme.hu/arrowhead/orchestrator:latest      "/bin/sh -c 'cd /orc…"   30 hours ago        Up 30 hours         0.0.0.0:8441->8441/tcp, 0.0.0.0:38441->8441/tcp   orchestrator
ba93c85f13bd        portus.arrowhead-ci.tmit.bme.hu/arrowhead/authorization:latest     "/bin/sh -c 'cd /aut…"   30 hours ago        Up 30 hours         0.0.0.0:8445->8445/tcp, 0.0.0.0:38445->8445/tcp   authorization
37f7b067b5f6        portus.arrowhead-ci.tmit.bme.hu/arrowhead/serviceregistry:latest   "/bin/sh -c 'cd /ser…"   30 hours ago        Up 30 hours         0.0.0.0:8443->8443/tcp, 0.0.0.0:38443->8443/tcp   serviceregistry
c7168fdcc98c        portus.arrowhead-ci.tmit.bme.hu/arrowhead/eventhandler:latest      "/bin/sh -c 'cd /eve…"   30 hours ago        Up 30 hours         0.0.0.0:8455->8455/tcp, 0.0.0.0:38455->8455/tcp   eventhandler
81de59b70356        mysql:5.7                                                          "docker-entrypoint.s…"   30 hours ago        Up 30 hours         0.0.0.0:3306->3306/tcp, 33060/tcp                 compose_mysql_1

**Comment by tsvetlin** [comment]
You solved your issue by including the `domain.name` and ,`domain.port` properties.

Thank you for pointing out, that the documentation was missing these two new properties. It was updated. It will be in the master branch next week.

Best wishes,
Svetlin
