### ISSUE TITLE
Changing the core system containers certificate location in config file

### ISSUE THREAD

**Issue by Towfiqomi** [eclipse-arrowhead/core-java-spring#151]
Hi,

Changing the location of the certificates is giving "Keystore URL doesn't exist"  error. 

server.ssl.key-store=classpath:certificates/authorization.p12
server.ssl.trust-store=classpath:certificates/truststore.p12

Needs a bit guiding on how to change these URLs. My current certificates folder is inside the docker folder.

Thanks in advance.

**Comment by tsvetlin** [comment]
Hello!

Thanks for the feedback, the instructions will be updated. 
You have to change the classpath to file and you have to provide the certificate as a volume to the container.

For example (service_registry property file):
```server.ssl.key-store=file:service_registry.p12```

docker-compose.yml:
``` 
volumes:
      - ./core_system_config/serviceregistry.properties:/serviceregistry/application.properties
      - ./core_system_config/serviceregistry.properties:/application.properties
      - ./tmit_certs/service_registry.p12:/serviceregistry/service_registry.p12
```

Best wishes,
Svetlin

**Comment by Towfiqomi** [comment]
Thanks a lot.
