### ISSUE TITLE
Insecure mode in Docker container

### ISSUE THREAD

**Issue by sumi0910** [eclipse-arrowhead/core-java-spring#153]
Hello,
 
I did change the server.ssl.enabled=true to false to start the framework in the insecure mode as mentioned in the README. But when I did restart every container, the port number is in odd values i.e. 8441,8443 etc but as per the 4.1.2 version, even ordering is for insecure mode and odd ordering is for secure mode. I am not sure whether my framework is in  secure or insecure mode due to port number which remains unchanged even after restarting after disabling the flag. Is there a way to ensure the changes are reflected

**Comment by borditamas** [comment]
Hi Sumi,

as 4.1.3 is not backward compatible to 4.1.2 you shouldn't use 4.1.2 documentations at all to dealing with 4.1.3.

In 4.1.3 the core systems are running on the port defined in the properties, no matter if the ssl is enbled or not.

You can check the core systems log files right after the start-up and there will be an entry about the security level OR if you can reach the core systems' Swagger via **http**://address:port then it is running on insecure mode, but if you reach it via  via **https**://addresst:port then it is running on secure mode.

**Comment by sumi0910** [comment]
Thank you for the information and quick response.
