### ISSUE TITLE
Do I need to add different sysop certificate after installing own created .deb files for Debian Buster?

### ISSUE THREAD

**Issue by XsylenZ** [eclipse-arrowhead/core-java-spring#157]
I used 4.1.2 until now, in unsecure mode, for my intern project. Now I need to run everything on the latest version so it stays transferable for another student in the near future.

I created some debian installable files (*.deb) from the java code with mavin, and installed it with the installation prompts and all, the provided *.deb files on git returned an error on Debian Buster).  After that I wanted to check any of the services through Chrome browser with Swagger, but it keeps complaining about the certificate(s).

I followed issue  #79 and #136 for a solution but Chrome keeps complaining about the certificate.

Do these solutions only apply to the docker version and/or Java .jar version and not when I install the core systems manually?

I changed the names in the installation to the ones that are in the sysop cert but it still won't allow me to enter it.

Can someone point me to the right direction how to use the certificates browser wise or is there some how-to that I overlooked?

Kind regards

**Comment by rbocsi** [comment]
Hi, @XsylenZ!

The Service Registry debian installer should generate the sysop certificate during the installation process. You can find it in the /etc/arrowhead/systems/sysop directory.

**Comment by XsylenZ** [comment]
Thanks for the confirmation on this, I already tried this before the weekend but somehow I'm not able to read the certificate but still can add it to the system (MacOS).

![image](https://user-images.githubusercontent.com/10152270/70436159-f23a4180-1a88-11ea-9d20-cd7bd22b355b.png)

Now it does work like it should. Thanks!
