### ISSUE TITLE
Error 503 during orchestration

### ISSUE THREAD

**Issue by pyXos** [eclipse-arrowhead/core-java-spring#158]
Hi!
I am trying to set up Arrowhead using Docker as described in the readme (only using Orchestrator, Authorization and Service Registry). Setting up a provider and creating the auth-entry seems to work fine (confirmed with GET requests after the POSTs). 

Now I wanted to set up a consumer for the previously created service. I am always getting this error when posting to `orchestrator/orchestration`:  

`{"errorMessage":"Could not get any response from: http://0.0.0.0:8444/authorization/intracloud/check", "errorCode":503,"exceptionType":"UNAVAILABLE"}`

`/authorization/intracloud/check` from the same place works though, and I get a response as expected with the auth entry created before. The Authorization node is definitely running and  shows that it received and processed the `check` without any errors in the DEBUG log. 

The Orchestrator log says 
```
HTTP POST http://0.0.0.0:8444/authorization/intracloud/check
Accept=[application/json, application/*+json]
Writing [eu.arrowhead.common.dto.internal.AuthorizationIntraCloudCheckRequestDTO@14711d6b] as "application/json"
UnavailableServerException occurred at http://0.0.0.0:8444/authorization/intracloud/check
Using @ExceptionHandler public org.springframework.http.ResponseEntity<java.lang.Object> eu.arrowhead.common.http.ArrowheadResponseEntityExceptionHandler.handleArrowheadException(eu.arrowhead.common.exception.ArrowheadException,org.springframework.web.context.request.WebRequest)
Found 'Content-Type:application/json' in response
Writing [ErrorMessageDTO [errorMessage = Could not get any response from: http://0.0.0.0:8444/authorization/i (truncated)...]
Resolved [eu.arrowhead.common.exception.UnavailableServerException: Could not get any response from: http://0.0.0.0:8444/authorization/intracloud/check]
Completed 503 SERVICE_UNAVAILABLE
```

Do you have any idea what's going on here?
Thanks!
-Mario

**Comment by pyXos** [comment]
Additional note:
I am using `"pingProviders": "false"`. When it is set to `true`, I don't get any errors but also just an empty response. The provider service is definitely reachable though, I can successfully call it manually (bypassing the orchestrator).

**Comment by borditamas** [comment]
Hello, 
the problem is that ip '0.0.0.0'  means nothing when you have trying to reach the core system out of the docker network. Some days ago we made a new feature for covering these hosting difficulties, so please  update your core systems for the latest available and set the new domain.name ad domain.port poperties in the config file.

**Comment by pyXos** [comment]
Thanks, I could fix it with this hint!
