### ISSUE TITLE
Provider system name and certificate common name do not match

### ISSUE THREAD

**Issue by Towfiqomi** [eclipse-arrowhead/core-java-spring#162]
Hi,

Trying to solve the issue, but need your help. Getting the following error while registering service from swagger UI from the browser.

{
  "errorMessage": "Provider system name(tow1) and certificate common name (sysop.tow1.tuni.arrowhead.eu) do not match!",
  "errorCode": 401,
  "exceptionType": "AUTH"
}

JSON Payload:
{
  "endOfValidity": "2019-12-05T12:00:00",
  "interfaces": [
    "HTTP-SECURE-JSON"
  ],
  "metadata": {
    "unit": "celsius"
  },
  "providerSystem": {
    "address": "127.0.0.1",
    "authenticationInfo": "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC.................",
    "port": 0,
    "systemName": "tow1"
  },
  "secure": "CERTIFICATE",
  "serviceDefinition": "Temperature",
  "serviceUri": "temperature",
  "version": 0
}

Thanks in advance.

Regards,
Towfiq

**Comment by MaGaMeGa** [comment]
Hi Towfiq,

On the above example, you try to use the client endpoint, with sysop cert.

At the client endpoints, we do not allow registrations for anybody but the service provider system.
At the management endpoints, you can register things through bowser (with sysop certificate).

If you want to register your provider trough swagger, please use the management endpoints.

**Comment by Towfiqomi** [comment]
Thanks a lot for the explanations.
