### ISSUE TITLE
Docker registry unavailable

### ISSUE THREAD

**Issue by ghost** [eclipse-arrowhead/core-java-spring#165]
I'm trying to access the Docker images mentioned in [docker-compose.yml](https://github.com/arrowhead-f/core-java-spring/blob/master/docker/docker-compose.yml#L17) but it seems like the Docker registry is unavailable:

```bash
docker pull portus.arrowhead-ci.tmit.bme.hu/arrowhead/serviceregistry:latest
```
yields
> Error response from daemon: Get https://portus.arrowhead-ci.tmit.bme.hu/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

Did anyone have similar issues?

Thanks!

**Comment by MaGaMeGa** [comment]
Hi, 
unfortunately, the servers are down and we do not know when they going to be up again.
I would suggest using the Debian installer in the meantime.

**Comment by MaGaMeGa** [comment]
https://github.com/arrowhead-f/core-java-spring/blob/master/documentation/deb-installer/DEBIAN-INSTALL.md

**Comment by tsvetlin** [comment]
Hello!

The main server had a PSU failure and it burned the motherboard too. It will be repaired soon. But we don't know exactly when.

Best wishes,
Svetlin

**Comment by ghost** [comment]
Thanks for the updates, @MaGaMeGa  and @tsvetlin ! I built the images and pushed them to a private Docker registry. That worked - thanks for publishing the docker-compose.yml etc.!

**Comment by tsvetlin** [comment]
The docker images are available in Docker Hub, docker-compose.yml has been updated accordingly.
