### ISSUE TITLE
Error in Orchestration response

### ISSUE THREAD

**Issue by sumi0910** [eclipse-arrowhead/core-java-spring#169]
Running car-demo and c++ example provides orchestration response with no details regarding the provider. This is what I see while running the C++ DEMO and also in Swagger UI. Similar is the case for car-demo example. 

Orchestration Response as {"response";[]}

According to my understanding, this is the issue with the orchestration process. Please let me know what can be the root cause for it as I am getting HTTP response code as 200

**Comment by borditamas** [comment]
As your are getting HTTP 200 most probably the authorization ruleas are missing. Or maybe there is no metadata match if you're orchestrating with metadata_search=true flag. Check these two hint please at first.

**Comment by sumi0910** [comment]
@borditamas thank you for the response. I checked the authorization rules and I haven't keep metadata_search=true.  Authorization rules seem fine, but now I am getting HTTP RESPONSE 401 i.e. Service definition name is not available in the database but on querying the services in Service Registry system, the service is registered and also authorization rules have been defined.
 
Used debian based installation.
the AHF is running on 192.168.128.19
the demo example is running on 192.168.128.39

Service registry providing information regarding registered services.
![image](https://user-images.githubusercontent.com/44111991/72808790-943d7400-3c5a-11ea-9acf-7440a0940fa7.png)

Authorization rules 
![image](https://user-images.githubusercontent.com/44111991/72808932-eb434900-3c5a-11ea-9b08-84d2b08f7c9f.png)

But when doing POST : https://127.0.0.1:8441/orchestrator/orchestration using the client certificate gives (sysop certificate is not used because of the "errorMessage": "Requester system name(client1) and client name from certificate (sysop) do not match!")

![image](https://user-images.githubusercontent.com/44111991/72809032-15950680-3c5b-11ea-9f70-dde5f5dd18e2.png)

**Comment by MaGaMeGa** [comment]
From the pictures you provided, we could not tell if you used secure/insecure settings consequently.
(You sent the request to https and you enabled token verification but your authorization rule is for http.)
Please, provide the application.properties files of the core systems and clients and the complete DB tables
and your orchestration flags settings so we could try to analyze your issue.

**Comment by sumi0910** [comment]
I am developing an application in C++.
DB table ( Note: Orchestration store is the empty set)
![image](https://user-images.githubusercontent.com/44111991/72817032-66abf700-3c69-11ea-8e95-89c6b0889efd.png)

Service Registry application.properties:
![image](https://user-images.githubusercontent.com/44111991/72817457-18e3be80-3c6a-11ea-833a-a4af9c4e1156.png)

Authorization application.properties
![image](https://user-images.githubusercontent.com/44111991/72817373-f18cf180-3c69-11ea-8438-ffc7c3ef8f87.png)

Orchestration application.properties
![image](https://user-images.githubusercontent.com/44111991/72817538-3ca70480-3c6a-11ea-878f-137e6a53676a.png)

The consumedService.json consists of 

{
	"consumerID": "client1",
	"requestForm": {
		"orchestrationFlags": {
			"overrideStore": true
		},
		"requestedService": {
			"interfaceRequirements": [
				"HTTP-INSECURE-JSON"
			],
			"securityRequirements": [
				"TOKEN"
			],
			"serviceDefinitionRequirement":
				"IndoorTemperature_ProviderExample"
		},
		"requesterSystem":
		{
			"address": "192.168.128.39",
			"port": 8585,
			"systemName": "client1"
		}
	}
}

And the client OrchestrationInterface.ini consists of the IP address of itself and the Orchestration system 

[Server]
or_base_uri="http://192.168.128.19:8441/orchestrator/orchestration"
or_base_uri_https="https://192.168.128.19:8441/orchestrator/orchestration"
port="8585"
address="192.168.128.39"
address6="[fe80::1a57:58d9:c43e:6319]

As I don't know how to add authentication information regarding the client while registrating into DB, provided its authentication info=""  but I do have created self-signed client certificate and added in the browser.

**Comment by MaGaMeGa** [comment]
Please also attach the other relevant tables ...

**Comment by sumi0910** [comment]
![image](https://user-images.githubusercontent.com/44111991/72842712-367c4c80-3c99-11ea-85a9-1576b17a44a1.png)

Let me know if at all any table i m missing

**Comment by sumi0910** [comment]
![image](https://user-images.githubusercontent.com/44111991/72842931-cd490900-3c99-11ea-8b33-b5d5d4807415.png)

let me know if  i am missing any other table

**Comment by MaGaMeGa** [comment]
Thank you for attaching the names of the tables.
You have it all, nothing missing there.
It would be a great advantage in the table content verification process if you could also attach the content of the tables.

To add authentication info you have to use the public key of your systems certificate.
( You don't need the BEGIN PUBLIC KEY prefix and the END PUBLIC KEY suffix and you have to eliminate all line breaks as well. )
You can find an example of it at 
 the "Acquiring Authorization Info" part of the README: https://github.com/arrowhead-f/core-java-spring/blob/master/documentation/gatekeeper/GatekeeperSetup.md

**Comment by sumi0910** [comment]
Thank you @MaGaMeGa for your response. 
Following are the details of the table

![image](https://user-images.githubusercontent.com/44111991/72885057-7b3ecc80-3d07-11ea-8654-645ae9ac7347.png)

![image](https://user-images.githubusercontent.com/44111991/72885036-6f530a80-3d07-11ea-8ccd-5614c061b06c.png)

As per you mentioned regarding acquiring authorization info, with respect to the certificate created for car-demo example, I am able to get the information but when it comes to certificate created for client-cpp example I am not able to extract the authorization info.

![image](https://user-images.githubusercontent.com/44111991/72885151-ac1f0180-3d07-11ea-9378-0948f956b9eb.png)

 In the c++ demo example, the .p12 file is converted into cacert.pem, clcert.pem, privkey.pem and publickey.pem .  
 On server 192.168.128.19 where AHF is deployed, I am using .p12 file in the chrome 
On server 192.168.128.39 where C++ is running , its using *.pem files. 
At present I am getting an error " The certificate of the system at https://192.168.128.19:8445/authorization/intracloud/check does not contain specified IP address or DNS name as a Subject Alternative Name" 
(Note: I did add the IP address and DNS Name of the Consumer along with local host, 127.0.0.1 i.e. client1 which is the name of the consumer and IP address as 192.168.128.39 and uploading same .p12 file on both the servers )

My doubt is whether I have to use *.pem files on the server AHF is deployed or is there any other way to resolve this issue.


(NOTE: Earlier i was getting HTTP response as 200 , but now I am getting Error code : 401 after changing the application properties domain.name: 192.168.237.137 to 192.168.128.19 and restarted the services using the command sudo systemctl restart arrowhead-\*.service )

**Comment by MaGaMeGa** [comment]
You should set authentication info for all systems.
It must be they correctly formatted public key.
You can abstract it from .p12 or from the publickey.pem of the system. 

Unfortunately, we could not verify the validity of the content of your DB tables:
there should have been entries in a lot of other tables too ...

**Comment by sumi0910** [comment]
Hey @MaGaMeGa and @borditamas , I resolved the error " The certificate of the system at https://192.168.128.19:8445/authorization/intracloud/check does not contain specified IP address or DNS name as a Subject Alternative Name"

Back to HTTP response 200, where the response is empty.No clue what is causing this issue because Orchestration and client system are in communication but after providing right authorization rules and verifying the table contents in the database leads to no response.

**Comment by MaGaMeGa** [comment]
Hey @sumi0910 
According to the fragments you sent earlier, it is very likely that ether or both your authorization rules and the table contents in the database are not valid. This could cause an HTTP response 200.
If you provide further information about your setting, we would be happy to help to analyze your issue.

**Comment by sumi0910** [comment]
Hey, thank you for being patient and replying to the issue. 
Here are the details of the table:
Details of the Tables:
![image](https://user-images.githubusercontent.com/44111991/72898225-f6ae7700-3d23-11ea-93c6-094b5aa643f2.png)

Details of the authorization rules 
![image](https://user-images.githubusercontent.com/44111991/72898202-eac2b500-3d23-11ea-9477-e1f3b9f1e7fd.png)

Details of the service definition
![image](https://user-images.githubusercontent.com/44111991/72898139-cf57aa00-3d23-11ea-80d2-4db23b58ab64.png)
 :

Details of systems_:

![image](https://user-images.githubusercontent.com/44111991/72898073-b18a4500-3d23-11ea-91de-31f8b2172301.png)

**Comment by MaGaMeGa** [comment]
Please also attach the authorization_intra_could_interface_connections tables data.

**Comment by sumi0910** [comment]
Here you go,
![image](https://user-images.githubusercontent.com/44111991/72901079-5f4c2280-3d29-11ea-9a50-b638f5e74640.png)

**Comment by MaGaMeGa** [comment]
Please also attach the service_interface table data.

**Comment by sumi0910** [comment]
Yeah sure.

![image](https://user-images.githubusercontent.com/44111991/72904029-86f1b980-3d2e-11ea-82c3-b0091a8d6dee.png)

**Comment by MaGaMeGa** [comment]
Thank you for the **service_registryinterface_connection** tables content. 
In order to help you to analyze your issue, we should also see  the **service_interface** table data.

**Comment by sumi0910** [comment]
Yeah sure

![image](https://user-images.githubusercontent.com/44111991/72911068-bd810180-3d39-11ea-94c6-d42cf051c86c.png)

**Comment by MaGaMeGa** [comment]
Based on the information you provided,
you do not have a valid authorization rule.

You registered a get-car service (id:19) for the car_provider_demo system (id:33) with secure: TOKEN with metadata filled and with HTTPS-SECURE-JSON interface (id: 15).
In your authorization_intra_cloud there is no record for service_id: 19.

You have a record in authorization_intra_cloud for service_id: 18.
But in your service_registry there is no record with service id: 18.

-----------------------------------------------------
service_interface

service_interface id:2 value: HTTP-INSECURE-JSON
service_interface id:15 value: HTTPS-SECURE-JSON

-----------------------------------------------------
service_registry_interface_connection

service_registry_interface_connection id:818 service_registry_id: 818 interface_id: 15
service_registry_interface_connection id:1735 service_registry_id: 1735 interface_id: 2

-----------------------------------------------------
service_registry

service_registry_id: 818 service_id: 19 system_id: 33 secure: TOKEN metadata: ... 
service_registry_id: 1735 .... no record

-----------------------------------------------------
authorization_intra_cloud

authorization_intra_cloud id: 3 consumer_system_id: 39 provider_system_id: 33 service_id: 18

-----------------------------------------------------
authorization_intra_cloud_interface_connection

authorization_intra_cloud_interface_connection id: 3 authorization_intra_cloud_id: 3 interface_id: 15

-----------------------------------------------------
system_id

system_ id: 33 system_name: car_provider_demo ...
system_ id: 39 system_name: car_consumer_demo ...

-----------------------------------------------------
service definition

service_definition id: 19 service_definition: get-car

**Comment by sumi0910** [comment]
Hello @MaGaMeGa, thanks for the brief explanation and my sos-example is working and I tested it for create-car assuming that get-car will work if one of the services works and it did. I have been precisely focusing on c++ demo code and with respect to "indoortemperature_providerexample" service of the "securetemperatureprovider" provider, i did verify the contents of the table based on your comment mentioned above and it seems to me to that authorization rules are rightly put in database for c++ demo but I am getting orchestration response as "response: []". I have raised this issue under client-cpp demo also but no one seems to be replying there and majorly it's an internal issue of the orchestration process and i thought this is the right place where the issue should be. 

Note:  I am running c++ demo on raspberry pi and the service query form :

The consumedService.json consists of

{
"consumerID": "client1",
"requestForm": {
"orchestrationFlags": {
"overrideStore": true
},
"requestedService": {
"interfaceRequirements": [
"HTTP-INSECURE-JSON"
],
"securityRequirements": [
"TOKEN"
],
"serviceDefinitionRequirement":
"IndoorTemperature_ProviderExample"
},
"requesterSystem":
{
"address": "192.168.128.39",
"port": 8585,
"systemName": "client1"
}
}
}

MySQL database consists of all details of indoortemperature service in the above-provided images.
except definations of system_ which is provided below

![image](https://user-images.githubusercontent.com/44111991/72978519-e7d4cc80-3dd6-11ea-8363-b2c8383fa3b8.png)

Also the securetemperaturesensor and client1 are getting registered with authentication info as NULL and on changing the consumedService.json script parameter with respect to the "securityRequirement" as TOKEN/ CERTIFICATE gives orschestration response as HTTPS 200 OK with  "response":[]; and when the "securityRequirement" as NOT_SECURE gives error as 401 with error  " The certificate of the system at https://192.168.128.19:8445/authorization/intracloud/check does not contain specified IP address or DNS name as a Subject Alternative Name"

**Comment by MaGaMeGa** [comment]
The above-explained behavior is the expected behavior of the orchestrator if your authorization rules are not correct. It could not find any authorized provider, so it gives back an empty array.
It is not possible to require a token when the security is NOT_SECURE.
You could try to turn of token.security.filter.enabled in your providers and adjust your DB setting accordingly.

**Comment by MaGaMeGa** [comment]
You could also try to send this:
{
"consumerID": "client1",
"requestForm": {
"orchestrationFlags": {
"overrideStore": true
},
"requestedService": {
"serviceDefinitionRequirement":
"IndoorTemperature_ProviderExample"
},
"requesterSystem":
{
"address": "192.168.128.39",
"port": 8585,
"systemName": "client1"
}
}
}

**Comment by sumi0910** [comment]
when I send as per the above-mentioned JSON @MaGaMeGa I get this error 401 with " The certificate of the system at https://192.168.128.19:8445/authorization/intracloud/check does not contain specified IP address or DNS name as a Subject Alternative Name"

![image](https://user-images.githubusercontent.com/44111991/72985183-b283ab00-3de5-11ea-9d0f-b89d85d6b926.png)
![image](https://user-images.githubusercontent.com/44111991/72985280-eeb70b80-3de5-11ea-8cd1-f0ecceddb090.png)

**Comment by MaGaMeGa** [comment]
It means there is a problem with your authorization core system certificate.
Please send us your authorization.p12 for verification at arrowhead-dev.slack.com at /beginners chanel.

**Comment by MaGaMeGa** [comment]
To get access to arrowhead-dev.slack.com please contact: szvetlin@aitia.ai

**Comment by sumi0910** [comment]
Thanks, @MaGaMeGa for providing information regarding the access. I was trying all the ways to find if i have access or not, if not how to get..:P
