### ISSUE TITLE
Reduce RAM usage of Docker containers

### ISSUE THREAD

**Issue by emanuelpalm** [eclipse-arrowhead/core-java-spring#175]
Can something be done to reduce the RAM usage of the AHF core Docker containers? For example, could you create an env variable that could be set to disable SwaggerUI? Could the Java GC somehow be fine-tuned to make the containers consume less RAM?

I will need to run 21 Docker containers, representing two clouds with 6 core AHF systems, 2 AHF application systems, 1 management tool and 1 MySQL database, each. In addition, an AcitveMQ container needs to run to facilitate communication between the two clouds. All off these containers need to run from my laptop, which has only 16 GB of RAM. If I run 15 of these containers, together with my IDE and a browser, my RAM usage hovers around 95%. I've also had two random system crashes, both of which I believe to be related to the RAM issue. I will try to get more RAM to my laptop. However, I do believe more people ought to be interested in seeing the containers consuming less RAM, for the sake of running them on RPIs and so on.

**Comment by tsvetlin** [comment]
It would be great if you could help us out in that :)

**Comment by borditamas** [comment]
I think using virtual machines (docker) while the resource consumption is a key factor in your scenraio is not a good approach. I suggest to [compile the source code](https://github.com/arrowhead-f/core-java-spring#quickstart_compile) of the systems and run as plain java applications. You can also play a little with the [java memory allocation by the -Xmx and -Xms flags](https://java2blog.com/xms-xmx-parameter-java/), but do not forget that each core system is web server, which of course have reasonable needs.

**Comment by tsvetlin** [comment]
I completely agree with @borditamas. Docker is mainly meant for servers, where resources are not an issue, due to having (32/64/92GB of RAM). 

For your exact need using JARs would be the best approach, they use the least resources.

What you are suggesting would be a great addition to the framework, I'm sure we all can agree on that. Sadly our backlog is full and we don't have any free time to spare to implement this. 

@emanuelpalm What do you think, could you implement this feature and dive deeper into resource optimization on the Docker and Java side?

**Comment by emanuelpalm** [comment]
@borditamas I'm aware of the implications on RAM usage of using containers/virtual machines. @tsvetlin Yes, I think that is the more viable approach.

I have already spent some time making the management tool container requiring less RAM, or at least reduced its startup time and Docker image size. Generally, making the environment required to run a container less complicated should reduce RAM usage.

**Comment by emanuelpalm** [comment]
I believe a solution to this issue might be to create a single Docker image that contains all the core systems and a MySQL database. This should avoid most of the overhead imposed by Docker. It should be trivial to add environment variables functioning as flags for having certain systems not start. As they all live in the same container, I also believe it reasonable for them all to share the same certificate. I guess that could also be configurable by whoever creates a container from the image.

**Comment by MaGaMeGa** [comment]
Hi @Emanuelpalm
The current version of the AH Core Systems is based on the secure communication of the certified core systems. The will not be able to securely communicate without proper certificates.
The certificates by themself are only a few kilobytes and only loaded ones, so I do not think that the reducing of the number of certificates would mean 
any meaningful gain on the RAM usage.
My approach would be to run the core systems of the clouds in separate dedicated environments,
and focus on the RAM usage reducing on the (often resource-limited) client systems.

**Comment by emanuelpalm** [comment]
@MaGaMeGa My concern is not at all to run a production system-of-systems, but to run a development environment. The main reason I want to use Docker for that is to make my application easy to test against the Arrowhead Core services, both for myself and for anyone else interested in evaluating my application. 

Yes indeed, the certificates do not impose any significant overhead in terms of RAM. I had a vague idea about it somehow reducing the work required to set up an Arrowhead test could. I'm not so confident anymore, so I'll just ditch that idea.

**Comment by MaGaMeGa** [comment]
@Emanuelpalm
If you looking for a straightforward way to install a cloud with all the core systems certificates inclouded,
it may worth to give a try to https://github.com/arrowhead-f/core-java-spring/blob/master/documentation/deb-installer/DEBIAN-INSTALL.md
After you get used to the installation process you can set up an Arrowhead test cloud fairly easily.

**Comment by emanuelpalm** [comment]
@MaGaMeGa I want my test cloud not to require more ceremony than having to type `docker-compose up`. The Debian installers are great for production use, but that is not what I am after. I could have used the installers as the basis for my Docker image, but I ended up not using them. I'll make a pull request shortly. We can discuss the image there.

**Comment by emanuelpalm** [comment]
With #176 merged, I'm not going to spend any more time on this. I guess you guys could reopen it later if it would become relevant again, or maybe just create another issue.
