### ISSUE TITLE
Failed to bind properties under 'server.address' to java.net.InetAddress

### ISSUE THREAD

**Issue by Towfiqomi** [eclipse-arrowhead/core-java-spring#184]
Hi,

I am trying to start the core system via docker container. I am constantly getting this error.

```
gateway            |
gateway            | Failed to bind properties under 'server.address' to java.net.InetAddress:
gateway            |
gateway            |     Property: server.address
gateway            |     Value: gateway
gateway            |     Origin: URL [file:./application.properties]:19:16
gateway            |     Reason: failed to convert java.lang.String to java.net.InetAddress
```

Only the serviceregistry and event handler starts. Other core component fails.

Is there something I am doing wrong or things to modify. 

Thanks in advance.

**Comment by mileippert** [comment]
Check your gateway.properties configuration: Currently there is a space added to the server.address key for a few of those configuration files. Remove that space and the connection will work. 

more information: https://github.com/arrowhead-f/core-java-spring/issues/160#issuecomment-572087415

**Comment by Towfiqomi** [comment]
Thanks a lot for the help @mileippert. It worked.

Regards,
Towfiq

**Comment by ajoino** [comment]
The trailing spaces are still there and causing issues.
Specifically, the properties files of the authorization, orchestrator, gateway and gatekeeper core systems have a trailing space in the server.address definition
