### ISSUE TITLE
Session closed

### ISSUE THREAD

**Issue by fxk14i** [eclipse-arrowhead/core-java-spring#186]
Hello,

I managed to setup two local clouds that are connected by a relay (strictly following the guide setup 
gateway and gatekeeper), also the intercloud orchestration works, but the gateway's sessions will always be closed after one minute by the gateway.

Sessions directly after orchestration are attached, after one minute they are empty:

{
  "data": [],
  "count": 0
}

[response_1582279777193.txt](https://github.com/arrowhead-f/core-java-spring/files/4235582/response_1582279777193.txt)

**Comment by rbocsi** [comment]
Hi @fxk14i,

The ActiveMQ server closes all queuse (and hence the session) after one minute of inactivity (if you don't call the provider's endpoint). I suspect thats the reason of your problem. 
For testing this theory, please find this line in the config xml of the activemq:
`<policyEntry queue=">" gcInactiveDestinations="true" inactiveTimoutBeforeGC="60000"/>`
Set the inactiveTimoutBeforeGC to a higher value (it is in milliseconds). Restarting the activemq server may be required.

**Comment by rbocsi** [comment]
One more thing: we noticed the the inactiveTimeoutBeforeGC has a typo (missing e). Unfortunately, the documentation of activeMQ contains this typo as well (see [here](https://activemq.apache.org/delete-inactive-destinations.html)). So we don't know that this typo is in the documentation only or in the activeMQ's code as well.
If setting inactiveTimoutBeforeGC to a higher value has no effect, maybe you can try to fix the typo too.
Please let me know, if you had to fix the typo. We will fix the documentation if necessary.
