### ISSUE TITLE
HTTP-INSECURE-JSON in secure server

### ISSUE THREAD

**Issue by Towfiqomi** [eclipse-arrowhead/core-java-spring#191]
Hi,

I have a small query.

If the service registry, authorization rules, and store entries all the processes are done with the HTTP-INSECURE-JSON interface in a secure arrowhead instance. Will the orchestration work in that scenario.

Another thing when I am doing store based orchestration, how to start the orchestration process?

Thanks in advance.

Regards,
Towfiq

**Comment by borditamas** [comment]
Yes it will work, if your consumer sends the orchestration request with HTTPS to the Orchestrator.
For store based orchestration you have to set these orchestration flags:
```
TRIGGER_INTER_CLOUD=false
OVERRIDE_STORE=false
```
