### ISSUE TITLE
Avoiding stale service registry entries 

### ISSUE THREAD

**Issue by emanuelpalm** [eclipse-arrowhead/core-java-spring#192]
I recently noticed that a system can register the same service with the service registry over and over again, as long as it specifies a new port every time. This could be a problem if an application decides to let the operating system decide the port number for its system, as every time the system starts, it will register again with a new port. If a system is intermittent (i.e., is only active for shorter periods of time), this could cause the Service registry to fill up with stale entries.

A possible way of making it easier to avoid stale service registry entries might be to introduce a `PUT /serviceregistry/services/:id` endpoint for registration, where systems chose random ID:s themselves. Before registering, the system is assumed to store the ID to a file. If the system crashes and is started again, it reads the ID from the same file and then overwrites the existing service registry entry by calling `PUT /serviceregistry/services/:id` again with the same ID.

Only the system that created the entry should be able to overwrite it, which removes the possibility that a system has its service registry entry overwritten by some other system. It is quite trivial to generate secure random ID:s, and also to limit the length of the ID:s to a certain number of characters. If not wanting to generate ones own ID, a `POST /serviceregistry/services` endpoint could also be available for registering, which would respond with a `Location: /serviceregistry/services/<ChosenID>` header. The system would then be assumed to use the same URI in subsequent overwrite attempts.

**Comment by emanuelpalm** [comment]
By the way, I don't really see a problem with introducing new HTTP endpoints, as long as the old ones remain with their existing behavior. You could even use the `Warning` header to alert users of the old endpoints that they are deprecated (See https://tools.ietf.org/html/rfc7234#section-5.5).

An example of using the header could be `Warning: 001 - "Deprecated endpoint"`

**Comment by borditamas** [comment]
Thanks for your remark, we will take into consideration for Arrowhead v5. Any suggestions about how to cover entirely this issue only from FW side is welcomed. (Would be more robust by not letting this responsibility to the application systems)

**Comment by emanuelpalm** [comment]
@borditamas I'll think about it. I agree it would be better if there are fewer ways in which registering systems can mess up.

**Comment by emanuelpalm** [comment]
Considering the discussion @tsvetlin and I have with @nicnys-8 and the others about the needs of the Plant Description Engine, it seems to me like if _system_ registration will have to become mandatory. This could, perhaps, be leveraged  to make _service_ registration more lenient.

The following could be a possible registration procedure, if we assume that systems can only register once (#204):
1. A system registers itself by sending a message to the system registry, which replies with a unique identifier. If HTTP is used, the registration could be a `POST` and the reply include a `Location` header. In other words, sending something like `POST /systemregistry/systems` would lead to a `201 Created` (or perhaps even a `204 No content`) response including a `Location: /systemregistry/systems/<random-id>` header.
2. The same system then registers itself with the service registry by sending something like a `PUT /serviceregistry/services/<the-same-random-id-as-was-in-the-location-header>`. For the sake of simplicity, the random ID could be the hash of the system's certificate.

If, however, system registration becomes mandatory, I think we should discuss merging the device, system and service registry into a single system. I don't think I need to convince anyone that minimizing message passing is a great way of improving the scalability of distributed systems. If device, system and service information is highly interrelated, it makes no sense to separate the information into different systems. Additionally, registering the device, system and its services can then be done with a single message.

If a schema for deriving universal identifiers can be settled on, such as certificate fingerprints (sha256 hash of x.509 certificate in DER form), it becomes trivial to implement the "Registry" system as a distributed hash-table, which means that we can get the best possible kind of scalability.

**Comment by tsvetlin** [comment]
"I think we should discuss merging the device, system and service registry into a single system." We should definitely discuss bringing them closer, since Device/System/Service Registry has overlapping features, mostly writing into the same tables, doing similar things.

Regarding the original of avoiding stale service registry entries, I think @mzsilak has a better solution for that: #208

**Comment by emanuelpalm** [comment]
@tsvetlin I agree to the statement that @mzsilak's idea of online/offline is good and should be pursued for version 5.0, but his idea is complimentary to my proposal, not a replacement.

If registry entries are saved even as systems go offline, we are going to get _more_ problems with stale service entries, not _less_. The solution I see to that is to make it easier for systems to replace entries they have registered previously.

**Comment by tsvetlin** [comment]
I commented on #208 that, we should remove the offline entries after X amount of time has passed. This would solve the problem with stale issues. What are your thoughts on this?

If we use the offline, and removal after a time method, then the random ID can point to an entry which no longer exists. What you suggest is also a good idea and can be implemented, just this error should be handled.
If this ID does not exist, the client will get a 404 and it should register itself. 

@borditamas suggested: 
> Thanks for your remark, we will take into consideration for Arrowhead v5. Any suggestions about how to cover entirely this issue only from FW side is welcomed. (Would be more robust by not letting this responsibility to the application systems)

I agree with that, it would be more robust if this won't be the responsibility of the application system. I'd keep the unregister, but it is optional to use.

**Comment by emanuelpalm** [comment]
@tsvetlin Removing entries after a certain time is certainly something that should be done, but I do not think it is enough. We want the best possible quality information in the service registry at all time, within reason, because the performance of the cloud is going to depend on how fast systems can find each other.

If you do not want systems to choose their own identifiers, how about using the hashes of their certificates? In that case systems would not specify their own identifiers. The registration flow would look like this (if we assume that only services are registered):

__1. Consumer to Service Registry__
```http
POST /serviceregistry/services HTTP/1.1
```
The Service Registry calculates the hash of the certificate, which it retrieves during the TLS handshake, of the consumer (SHA256?). If existing entries exist associated with the same provider, which is uniquely identified by its certificate hash, those are deleted before the new entries are inserted.

__2. Service Registry to Consumer__
```HTTP
HTTP/1.1 204 No Content
```
The consumer does not even need to know that what its unique identifier is.

Service unregistration could work like this:

```http
DELETE /serviceregistry/services?provider=me HTTP/1.1
```

This would unregister all services associated with the provider making the call, which makes it a suitable call to make before a given system shuts down.

If wanting to unregister individual services, then that could work like this:

```http
DELETE /serviceregistry/services/<service-name> HTTP/1.1
```

Or like this:

```http
DELETE /serviceregistry/services?names=<service-name-1>,<service-name-2> HTTP/1.1
```

**Comment by tsvetlin** [comment]
Great! This idea gets better with every iteration. Using a hash is a better solution. But this breaks INSECURE mode.

A system can only unregister it's own services, so the provider=me is unnecessary. It could be just like:

```http
DELETE /serviceregistry/unregister HTTP/1.1
```

This removes all services of the current provider system.

For individual services: serviceDefinition is not unique, if a system offers the same service on different ports, it would remove all of them. Thats why we need currently to specify: address, port, serviceDefinition, systemName.

What if, we keep the current unregister, add the functionality to call it without query params, this will remove every entry of the provider system. We know who the provider because of the certificate.

What do you think of this?

After this, INSECURE mode?

**Comment by emanuelpalm** [comment]
@tsvetlin I guess `?provider=me` is not strictly required, but it communicates to the humans that deletion is restricted to those services where the caller is the provider. Do as you wish. It is not a big deal. ;)

The only times you would be interested in removing some provided services, but not all, is when (A) services are ephemeral (live and die during short time spans that are different for different services provided by the same system) and (B) when services can be replaced while a system is running, due to upgrades or similar. Out of these, I guess A is the only use case of primary concern. As long as it is possible to register and unregister individual services, we should be fine.

INSECURE mode is a tough one. I don't know right now. As security is not a concern, how about providers choosing their own random identifiers? Not ideal, but at least an option.

**Comment by emanuelpalm** [comment]
Another idea is that since we are talking about an insecure system in any case, why no let any system just use:
```http
DELETE /serviceregistry/services/<service-name>?system=<system-name> HTTP/1.1
```
The name of the deleting system has to be specified somehow, as there would otherwise be no way for the service registry to know what service to deregister.

**Comment by emanuelpalm** [comment]
@tsvetlin An alternative to providers using their own random identifiers in INSECURE mode is for the _service registry_ to give the system a "secret" random number upon registration, which can later be used to deregister.

**Comment by tsvetlin** [comment]
Service Registry Heartbeat is configurable in the application.properties file, which runs a periodic task to unregister stale entries.
