### ISSUE TITLE
Use the ISO8601 format for time strings

### ISSUE THREAD

**Issue by emanuelpalm** [eclipse-arrowhead/core-java-spring#193]
The `endOfValidity` field of the [`ServiceRegistryRequestDTO`](https://github.com/arrowhead-f/core-java-spring/blob/master/core-common/src/main/java/eu/arrowhead/common/dto/shared/ServiceRegistryRequestDTO.java) message uses a non-standard date/time format. I would recommend strictly adhering to ISO8601, as it would guarantee compatibility with a wider array of tools.

The ISO8601 format requires, among other things, that a `T` be inserted between the date and time of a common timestamp, and a `Z` be inserted at the end (if UTC), as in `2020-03-18T22:13:32.143Z`. Those letters are missing from the timestamps you expect and provide.

By the way, the `java.time.Instant` class in the Java standard library correctly generates and parses ISO8601 date and time strings.

**Comment by tsvetlin** [comment]
Every date should be consistently formatted using [ISO8601](https://en.wikipedia.org/wiki/ISO_8601).

**Comment by tsvetlin** [comment]
This information should be in the IDD.

**Comment by rbocsi** [comment]
bump

**Comment by MaGaMeGa** [comment]
Resolved by rbocsi at arrowhead-f/core-java-spring branch. Waiting for review and close.
