### ISSUE TITLE
Token CID (Consumer IDentifier)

### ISSUE THREAD

**Issue by emanuelpalm** [eclipse-arrowhead/core-java-spring#197]
My understanding is that a full system certificate name, specified as the only Common Name in the subject distinguished name of a x.509 certificate, must be formatted as such:
```
     system-14.cloud-1.the-company.arrowhead.eu
     |_______| |_____| |_________| |__________|
         |        |         |           |
       SYSTEM   CLOUD    COMPANY      MASTER
```
No individual part, except for the MASTER, may contain any dots. Apart from this formatting, the system certificate must be issued by the cloud named `cloud-1.the-company.arrowhead.eu`, which in turn must be issued by the company named `the-company.arrowhead.eu`, which, lastly, must be issued by the master `arrowhead.eu`. All the issuers must have x.509 subject CNs with those exact names.

I've noticed that mostly just the SYSTEM part of the certificate name is used. However, in the [CID field](https://github.com/arrowhead-f/core-java-spring/blob/master/authorization/src/main/java/eu/arrowhead/core/authorization/token/TokenGenerationService.java#L195-L205) of the tokens you issue contain not just the SYSTEM part of the certificate name, but also the CLOUD and COMPANY parts.

Why not just the SYSTEM? If the token must originate from the same cloud, the system authorizing the token can simply check whether or not the consuming system has the same chain of issuers as itself.

Why not all four parts? If you want tokens to be useful outside the clouds in which they are issued, why assume that all local clouds have a connection to the `arrowhead.eu` certificate?

**Comment by borditamas** [comment]
Cloud information is necessarry due to the inter-cloud service consumption possibility. The fact that a provider was capabel to extract the token info (decrypt with its own private key and verify with the public key of Authorization Core system) proves that it is arrowhead compliant.

**Comment by emanuelpalm** [comment]
@borditamas I, currently, have no doubts about the security of the schema, as it is currently employed. It is rather on the verge of overkill, but that's a topic for another time. ;)

You mention, however, that tokens must be useful outside the local clouds in which they are issued, which is new to me. Then my question is: why only `<system>.<cloud>.<company>`? Why not go all the way and include the entire certificate CN? That makes it more straightforward to compare the CID against the CN of the consuming system. Right now I simply check if the consumer CN begins with the CID + ".". Even if I can't think of any obvious ways in which that particular procedure would be insecure, it would feel more rigorous to simply compare the entire common name with the CID.

**Comment by borditamas** [comment]
Actually tokens always generated in the same cloud where the belonged provider is located. It's just passed to the requester cloud during the inter-cloud orchestration process.

I agree that it would be more straightforward to simply compare the CN to the CID, but due to the fact that token is passed as a query parameter, we wanted to keep the size of JWT as small as it is possible.

**Comment by emanuelpalm** [comment]
@borditamas Alright. That's a good point. Keeping JWTs small is important.

Can it be properly assumed that no other master certificate will be used other than the "arrowhead.eu" one? Or, rather, that intercloud service consumption always will occur between systems with certificate chains that can be traced back to the same master certificate? I guess that should be the case, right?

If so, then you have answered my questions and you can close the issue. Thank you. :)

**Comment by borditamas** [comment]
Yes that's the case. All the core systems have a proper certificate validation process (including the arrowhead master) in place regardless of the request is coming from an application system or from an other core system. Since inter-cloud orchestration is managed by the Orchestrators, the Gatekeepers (via Relay) and the Authorization, then counsumers' and providers' certificates must be originated from the same master cert.
