### ISSUE TITLE
EventHandler subscription error codes

### ISSUE THREAD

**Issue by emanuelpalm** [eclipse-arrowhead/core-java-spring#206]
Currently, if a system starts an event subscription, crashes, and then attempts to subscribe again for the same event, the EventHandler replies with the following:

```http
HTTP/1.1 400

{
  "errorMessage":"Subscription violates uniqueConstraint rules",
  "errorCode":400,
  "exceptionType":"INVALID_PARAMETER"
}
```

While it is clear to me what is happening, there is no identifier in this response that can be unambiguously interpreted by a machine that no subscription is needed because one already exists.

**Comment by emanuelpalm** [comment]
This issue is very much related to #205.

**Comment by mzsilak** [comment]
In my opinion, such a business operation should be idempotent. 
The intention is to subscriber to an event. There should be no error if the system is already subscribed to the event.

**Comment by jenseliasson** [comment]
One simple solution is to return 
HTTP 201 CREATED if no subscription exists, and
HTTP 200 OK if a subscription already exists.

Neither of the two are error codes. But they do inform the client about the current, or rather previoues, status.

**Comment by emanuelpalm** [comment]
@jenseliasson When would it be relevant for a consumer to be able to distinguish between those two cases? If there is no need to, then always having the same return code is just a little bit less complicated.

**Comment by rbocsi** [comment]
bump

**Comment by MaGaMeGa** [comment]
Resolved by rbocsi at arrowhead-f/core-java-spring branch. Waiting for review and close.
