### ISSUE TITLE
Reachability of systems/services

### ISSUE THREAD

**Issue by mzsilak** [eclipse-arrowhead/core-java-spring#208]
The ServiceRegistry has a ProvidersReachabilityTask which removes all unreachable (i.e. no response from echo service) ServiceRegistry entries. 

I would propose to change this to a less drastic handling. Instead of deleting the entry, I would propose to flag it as "offline". After all, there could be actually a network issue or something else while the target service is still working. 
The same or a different task could regularly check the "offline" entries and mark them as "online" again once the issues are resolved. 

The "offline" flag would effectively act as filter and an offline system is not returned by system registry or orchestration service by default.

**Comment by tsvetlin** [comment]
It is a good idea. I'd keep the cleanup task, but merge with your idea. That means after an entry is flagged as offline, the cleanup task would only delete it after a specified amount of time being offline, eg. 24h. 
This way, we can still have the option to remove stale entries and not remove them if they only had network troubles.

**Comment by tsvetlin** [comment]
Thinking this through, this leads to an ambigous behaviour. Best choice is to remove them, when the system comes online again, it will register itself again.
