### ISSUE TITLE
The documentation needs better description on how to create the provider and consumers

### ISSUE THREAD

**Issue by epmplm** [eclipse-arrowhead/core-java-spring#217]
documentation for creating the provider, consumer , publisher and subscriber there should be much clearer than what it is now. The current repository just says look at the code? I think thee should be a document that says 
How to create a service register request, 
which api should be used, 
how to add parameters to the requests
naming conventions  
how to register the request in the service registry

etc...

these descriptions are missing.

**Comment by tsvetlin** [comment]
Are you aware of these options? (Java)
* https://github.com/arrowhead-f/sos-examples-spring
* https://github.com/arrowhead-f/client-skeleton-java-spring
* https://github.com/arrowhead-f/arrowhead-kalix

**Comment by epmplm** [comment]
Yes, but still they are just code with some notes. There is no description of the steps that should be taken to create one of the mentioned components. Something like
To create a provider in AHF do
1-
2-
3-
...

**Comment by tsvetlin** [comment]
With knowledge about how the framework works, it is really straightforward to do.
It can be a good starting point for newcomers. Would you like to submit a PR with those steps in the documentation?

**Comment by epmplm** [comment]
We have a PR on how we did it and I can make it so it is less specific to our sw. Or I can just send it to you?

**Comment by tsvetlin** [comment]
Please make it general, so it would suit most of the community. Thank you!

**Comment by epmplm** [comment]
ok no problem

**Comment by tsvetlin** [comment]
@epmplm Any updates on that?

**Comment by epmplm** [comment]
@tsvetlin  I have the first version of the document, would you like to review it?

**Comment by tsvetlin** [comment]
Yes, please.

**Comment by epmplm** [comment]
This is the what I have done so far 
[AHF Client development.docx](https://github.com/arrowhead-f/core-java-spring/files/4642422/AHF.Client.development.docx)

**Comment by tsvetlin** [comment]
It would be beneficial to create a step by step tutorial with increasing difficulty, starting from a single provider, ending with a fully fledged inter cloud scenario. A “tutorial” progression draft will be created and will be presented for review.

**Comment by ajoino** [comment]
I did something similar with the python client library [https://arrowhead-client-python-library.readthedocs.io/en/latest/quickstart.html](https://arrowhead-client-python-library.readthedocs.io/en/latest/quickstart.html).

Basically I modified the docker-compose.yaml to only contain the mandatory core systems, and created [a script](https://github.com/arrowhead-f/client-library-python/tree/master/examples/quickstart) that will start them and initialize the orchestration and authorization rules so the examples can be run without hassle. I think that perhaps we should have one or more example local clouds that can be used for learning. This would make the examples across all languages and frameworks similar and maybe help people understand the framework better. What do you think about that?

**Comment by rekikfadwa** [comment]
> This is the what I have done so far
> [AHF Client development.docx](https://github.com/arrowhead-f/core-java-spring/files/4642422/AHF.Client.development.docx)

Hi, can I have access to the Doc please ? I m begenning the implementation of an AH client and that what I need !

**Comment by tsvetlin** [comment]
https://github.com/eclipse-arrowhead/core-java-spring/files/4642422/AHF.Client.development.docx

@rekikfadwa
