### ISSUE TITLE
Debian installer: Choose network interface for certificate SAN's when installing core-common

### ISSUE THREAD

**Issue by ghost** [eclipse-arrowhead/core-java-spring#218]
Currently when installing `core-common` with the debian installer and selecting detached installation the system ip is retrieved by taking the ip of the second network interface, see the following snippet:

https://github.com/arrowhead-f/core-java-spring/blob/7e89135648ab00de68c481fddf0c7a0ac8381afa/core-common/src/deb/ahconf.sh#L16

There are many cases where the second network interface isn't the one with the correct  ip address. Virtualbox, for example, requires the second interface to be used as NAT.

I propose to add an option for the user to enter a custom ip address or to leave blank for default ip address (selected with the above snippet).

**Comment by ghost** [comment]
Another way to solve it:
During installation of core-common, list the network interfaces and let the user input a number corresponding to the correct network interface. Store the number as a config variable and replace `NR==2` with `NR==${interfacenumber}` or something along those lines.

**Comment by tsvetlin** [comment]
This feature was added by @EdvinAkerstrom and was released.
