### ISSUE TITLE
Missing network interface management

### ISSUE THREAD

**Issue by jenseliasson** [eclipse-arrowhead/core-java-spring#222]
If a provider registers multiple IP addresses for a service, there is no IP address matching when I client performs a query.

For example; if a service is registered with two entries
127.0.0.1  - "historian"
192.168.0.142 - "historian"

When a client, say with address 192.168.0.46) queries for "historian", the IP first address is returned (127.0.0.1). This causes the client to try to connect to its' own localhost.  What is needed is a matching function that returns the best IP address to a client that matches the source IP of the client.

The Service registry/Orchestrator must also handle these special cases with "special" IP addresses like "127.00.1", multicast, broadcast, etc and not allow a client to register services on those addresses.  A producer at 192.168.0.100 should not be allowed to insert 127.0.0.1 etc as an entry.

**Comment by borditamas** [comment]
Thanks for the proposal, yes we should implent it in v5.0.

**Comment by emanuelpalm** [comment]
This is a tricky problem that needs a robust solution. While I'm sure you are aware already, I just want to flag for anyone else that might be less informed. It essentially boils down to having to determine what kind of network a given system is on (localhost, intranet or Internet) and then making sure that the correct IP address is served to each system asking for orchestration. The hard problems arise when a system on an intranet wishes to consume a service on another intranet, as this requires NAT hole-punching. If we consider NAT out of scope, then I guess it gets simpler.

By the way, is an Arrowhead local cloud allowed to consist of multiple intranets?

**Comment by borditamas** [comment]
>  The hard problems arise when a system on an intranet wishes to consume a service on another intranet, as this requires NAT hole-punching.

This is the situation when [Gatekeeper](https://github.com/arrowhead-f/core-java-spring/tree/development#gatekeeper) and [Gateway](https://github.com/arrowhead-f/core-java-spring/tree/development#gateway) Core Systems and their Relays comes into the game.

**Comment by jenseliasson** [comment]
Agree, Gatekeeper and Gateway should handle all external access. So we just need a method to bind a system's services to the proper network interfaces. Edvin is working on an awesome solution for this @EdvinAkerstrom

**Comment by emanuelpalm** [comment]
@borditamas @jenseliasson Does that mean that a single local cloud __never__ consists of multiple intranets (i.e. NAT is never required within a cloud)? If so, I believe it should be listed as a requirement in the Eclipse Arrowhead standard.

**Comment by borditamas** [comment]
@emanuelpalm I woud say yes. Within a local cloud application systems have to have reachable via the addresses registered in the Service Registry.

**Comment by tsvetlin** [comment]
IP Filtering will be added in 4.4
Application properties will contain a flag, that will enable / disable localhost IP addresses, for development mode.

**Comment by borditamas** [comment]
bump

**Comment by tsvetlin** [comment]
Related to: #265
