### ISSUE TITLE
Service Registry register request input/output name change

### ISSUE THREAD

**Issue by jenseliasson** [eclipse-arrowhead/core-java-spring#223]
In the markup documentation for the Service registry, the endpoint **/serviceregistry/register** has an ServiceRegistryEntry message as input. The output is also named ServiceRegistryEntry. But the two messages are quite different. 

In the Java code, they are named ServiceRegistryRequestDTO  and ServiceRegistryResponseDTO, which makes more sense.

I propose that the documentation is updated and that the names **ServiceRegistryRequest** and **ServiceRegistryResponse** are used instead of **ServiceRegistryEntry**.

**Comment by tsvetlin** [comment]
Hello!

We can do that. It has the same name because of historical reasons. We should definitely do that in 5.0

**Comment by tsvetlin** [comment]
This name change was included in the 4.3 documentation.
