### ISSUE TITLE
Things missing from the compile section

### ISSUE THREAD

**Issue by epmplm** [eclipse-arrowhead/core-java-spring#242]
1. In the dependencies section for Mysql it does not say which engine type and authentication type should be selected.
2. **Got** to the scripts folder should be Go to.
3. It only says that you have to run the create_empty_arrowhead_db.sql script, but from my experience if you only do that the service users will not be able to access the db. So the document should also say to execute the create_arrowhead_tables.sql script
4. It does not say that you have to install the sysop certificate, and the certification section is after migration section. So I propose that before the section on how to start the services and the urls of each service, the document says that the user must add the sysop certification according to this section (https://github.com/arrowhead-f/core-java-spring#system-operator-certificate)

**Comment by tsvetlin** [comment]
1. MySQL version 5.7 should be used, It is stated in the documentation.
2. I'll fix this.
3. I'll fix this.
4. You only need the sysop certificate if you wish to poke around in the core systems manually.

Thank you for reporting these issues!
