### ISSUE TITLE
Typo in the example certificate (testcloud1/event_handler)

### ISSUE THREAD

**Issue by jara001** [eclipse-arrowhead/core-java-spring#251]
Hello,
   example certificate for the `event_handler` in `testcloud1` is created with a typo in the CN.

The field contains `event_handler.testcloud1.aitia.arrohead.eu` instead of `event_handler.testcloud1.aitia.arrowhead.eu`.

J.

**Comment by borditamas** [comment]
Thanks for the notice. Fixed by 6907ddece5f0e530931e06cb13749b90434a55bd
