### ISSUE TITLE
Error when requesting Onboarding with Name 

### ISSUE THREAD

**Issue by lelleib** [eclipse-arrowhead/core-java-spring#252]
The "onboarding with name" request does not work (tested with provided test keys). This may be because getFile() does not work in case of resources inside a jar file. (core-common/src/main/java/eu/arrowhead/common/SecurityUtilities.java:createCertificateSigningRequest)

The request:
`curl -X POST "https://localhost:8435/onboarding/certificate/name" -H  "accept: */*" -H  "Content-Type: application/json" -d "{  \"creationRequestDTO\": {    \"commonName\": \"canfilter\",    \"keyPairDTO\": {      \"keyAlgorithm\": \"\",      \"keyFormat\": \"PKCS#8\",      \"privateKey\": \"MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC4IeGH1hdAfmwXdu07vxhFdztdMn1kjbcHOrWR8mntoAVyOX4UqA41seyO2SRqqwyGdtYdV9q5J0eEBMJY/xfwxXSMeHonDmCi6WfscI6y3tPmRa/JnBO9CUWOuPONg8D0PAVxTv/I3SeGC/OUVwClW36ec/wY1RzQZmGoXFPAfmNRZa49b4fmvujLi9VsyMIodrtrRTcnA4bBV9E7WuxI1glgnrUtugwikmHG/s903J8e6UN4nMaRhZKwdT1F5OTPn6/vYLyTemy3VscdapMdf26XkvmWyJhRuKEztrddZ3iu7Bfbk/jKuO5sks044OONR2vp8lRa2Gd7Kq7EDwk3AgMBAAECggEAOZi/h1H8q/vfq+dTheDcor4NH7Xva0i4+9Xtfd2qLN5lVbmOKr/20ez55iUeMw+WN2lsyHj2vfv/btheQqBoyLO7JUV6UEU7DTqde2Qp/uGcvucFebcMpZEE5QQNizKvZLZxrWPctuQWvON4KeqdFRxtmvsE3G+tN7MO0S8wM4HM9y+DMm2/fOpvu/HwOUdAjCwINRnc451tTxLM1CmeNyFiJBIO73kAs6kJ1E1I1oKH8yO9/6CkmDLeCdpezLtNqUpGmBdAhnaSBvv/zQcLDsJzrn+DynOqZIyW0W+ngXfCj0P9GNkzkI9GXVEDs/lU3QPzVeWqsyqmqJccBKnY4QKBgQDusfP88BVSMl4iUusBbYtSl8/sUY+/vQETkxA7IThgQkmBPpHJPKJ3s5yZuPvkDYlc8GaMJtyqvB947pCpjdRlqEoaDS7U/inUYRvbHLzMJIY5bjmZSOh7KeuCchYPcJwKiAuR5ohc/weiARDCifuesftrPd1pMhcpiPgyOfaj0wKBgQDFe0YBZlDx4zVPQgK6+zNSpoXi6rqWKmSK5r+FO0WiC3L9pmsxJ7CHPO/rJ1kFbka9cL/xK7ReDvMI9vxlRoyLrxo+sGuj+lPV9Qy7b+9DIPct21XZ3GSfuavpFV1o7CeKPJLxypupqP2v9yEfpn2o4S5TxJhh+5UDKbiMRuM6jQKBgQCKEtpGWEKdF5GoXTqfytQq5LJbyxpSGWzD+/AJpD/OPsnyP1VpiO+aOoW9zmm3E7V/03geXmSLRuMVuzpnOinA3EZxJ2sNvjBIMBxC9S6pD/+svPwIlUoV5Lvc602jhMpetS+sKCR9VvD9X4xoXBT3SZFcCZ9IOLd5SUf5Fdp8DQKBgAdX5ymEKXxlK4VP+hQD5Uusf4wJmHifCPAVVofYxWUaMeN2vcOtKyZMQMuowemuyRigSbLpIiLhQW5S6N3HOtCy6THtk4MceuOY4ilSJz6Cyk49OrsINAGwgNEBB2EwbuP4DqrJEvLDIvPZJ7Uqlr+h5/wbcmMqXMcqVP96X1a9AoGAGaiWIyXj9KKuEySWVc0covgex2jMNtUI+2IIWXvBtuCq+8gkAnpa7fWlsra1JcDifc4UzgjqeJJat/07WcwAzYQR3J70PEXnjc0gAjArrDdsvcXeRrgVgLW7bZtmC+3+anW6G8ZRZMilPeopSa3VRdgN4la7/C7AIrGls85tq64=\",      \"publicKey\": \"MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuCHhh9YXQH5sF3btO78YRXc7XTJ9ZI23Bzq1kfJp7aAFcjl+FKgONbHsjtkkaqsMhnbWHVfauSdHhATCWP8X8MV0jHh6Jw5gouln7HCOst7T5kWvyZwTvQlFjrjzjYPA9DwFcU7/yN0nhgvzlFcApVt+nnP8GNUc0GZhqFxTwH5jUWWuPW+H5r7oy4vVbMjCKHa7a0U3JwOGwVfRO1rsSNYJYJ61LboMIpJhxv7PdNyfHulDeJzGkYWSsHU9ReTkz5+v72C8k3pst1bHHWqTHX9ul5L5lsiYUbihM7a3XWd4ruwX25P4yrjubJLNOODjjUdr6fJUWthneyquxA8JNwIDAQAB\"    }  }}"`

**Comment by balintpeceli** [comment]
We got the following response from the Onboarding Controller:
```
{
  "errorMessage": "Unable to create certificate signing request: class path resource [certificates/onboarding_controller.p12] cannot be resolved to absolute file path because it does not reside in the file system: jar:file:/home/arrowhead/mzsilak/core-java-spring/onboarding/target/arrowhead-onboarding-4.2.0.jar!/BOOT-INF/classes!/certificates/onboarding_controller.p12",
  "errorCode": 500,
  "exceptionType": "ARROWHEAD"
}
```

**Comment by mzsilak** [comment]
This is an interesting case. Usually the certificate is outside of the jar file (i.e. debian installation). 
I will try to use the same mechanism as CertificateAuthority (`CertificateAuthorityUtils.getKeyStore()`) as a fix. CA uses "getInputStream" instead of "getFile".
