### ISSUE TITLE
Usage of certificates during onboarding procedure not clear

### ISSUE THREAD

**Issue by lelleib** [eclipse-arrowhead/core-java-spring#254]
It is not completely clear what the preferred method is for using onboarding certificates.
For example when requesting the "echo" endpoint of Device Registry with an Onboarding Certificate, it returns with certificate error (similarly as when sending echo request to System Registry with Device Certificate) and then requests sent to the "register" endpoint return the same error.
Also, when not requesting the "echo" endpoint of Device Registry with a sysop certificate first, the requests towards the "register" endpoint (using Onboarding Certificate) fail with the same certificate error.
The only way I managed to get working every request of the procedure without any error (and without the need of using sysop certificate everywhere) was the following:
- Firstly sending echo requests to the Device Registry and System Registry using sysop certificate (not clear why it is necessary)
- Then sending request to the Onboarding Controller for an Onboarding Certificate (using sysop certificate)
- Then sending request to the Device Registry for a Device Certificate (using Onboarding Certificate)
- Then sending request to the System Registry for a System Certificate (using Device Certificate)

**Comment by mzsilak** [comment]
Hello,

> For example when requesting the "echo" endpoint of Device Registry with an Onboarding Certificate, it returns with certificate error (similarly as when sending echo request to System Registry with Device Certificate)
Yes, that was not considered. I fixed this in Device Registry and System Registry.

>  then requests sent to the "register" endpoint return the same error.
It depends which "register" method is used. There is a regular register/unregister/query method which can be only used once a valid arrowhead certificate is used by the client. 
For onboarding purposes please use the onboarding methods which are presented in the answer from the onboarding controller. On the device and system registry it will be the endpoints `/onboarding/name` or `/onboarding/csr` depending on which method was used on the onboarding controller. Those methods issue the next certificate and register the device/system in one step.

> Also, when not requesting the "echo" endpoint of Device Registry with a sysop certificate first, the requests towards the "register" endpoint (using Onboarding Certificate) fail with the same certificate error.
I was not able to reproduce this with the demo code from Eisenstadt meeting.

The steps should be as follows:

- use one of the 4 onboarding endpoints on onboarding controller. If authentication is done through certificates, an arrowhead trusted certificate is needed ( /onboarding/certificate/... endpoints).
- store the onboarding certificate and URIs from the response for device registry (onboarding uri), system registry (onboarding uri) and optionally service registry (register uri) and orchestration service (orchestration uri).
- use the onboarding certificate on device registry onboarding uri. store returned device certificate
- use the device certificate on the system registry onboarding uri. store returned system certificate
- use system certificate to communicate with arrowhead

Hope this clarifies and helps. I'll submit a patch for the issue with echo.
