### ISSUE TITLE
Failing tests by default

### ISSUE THREAD

**Issue by z0rb** [eclipse-arrowhead/core-java-spring#260]
Hi,

Last year I ran into the disabled tests: https://github.com/arrowhead-f/core-java-spring/commit/8050cb90d0c5de8f7748405dab123509d5f925a4

I've tried simply running maven install locally on the most recent version too with failing tests. It would raise confidence if the tests were passing. The README also points to using -DskipTests but that doesn't seem right.

Any plans for this? If the problem is that integration tests are executed along with the unit tests, can they be extracted to a non-default profile? This way users aren't really sure if the software will function as intended or the tests just don't fit.

**Comment by MaGaMeGa** [comment]
Hi,
At the current version, some of the tests, relay upon the created DB.
It is about to be changed in version 5.0.

However, even in the current version, all test shall pass.
Please, specify which test fail after the initial DB creation, so we can fix the errors.
