### ISSUE TITLE
Missing null check when creating URI

### ISSUE THREAD

**Issue by jaivgar** [eclipse-arrowhead/core-java-spring#261]
Hello,

I was using the client-library to write my systems, and while making a call to one of its methods I received this exception

![From common NullPointerException](https://user-images.githubusercontent.com/44204948/91577538-21f7e500-e949-11ea-89e2-33216f4eda97.png)

```Java
public <T> T consumeServiceHTTP(final Class<T> responseType, final HttpMethod httpMethod, final String address, final int port, final String serviceUri, final String interfaceName, final String token, final Object payload, final String... queryParams) {
```

The last arguments "queryParams" is stated to be nullable in the Javadoc, but when called with queryParams = null I obtain a NPE, which I think comes from this line
https://github.com/arrowhead-f/core-java-spring/blob/f899985e9b990bea3cc47d04300e9bf12d8d74ce/core-common/src/main/java/eu/arrowhead/common/Utilities.java#L297

Regards,

**Comment by borditamas** [comment]
Hello,

many thanks for your note. Seems you are right indeed.
New version with the bug fix going to be released soon.

Br, Tamás

**Comment by borditamas** [comment]
[Client-Library v4.1.3.12 ](https://github.com/arrowhead-f/client-library-java-spring/packages/186709) have been released. Please upgrade your dependency and close the issue if everything working fine.

**Comment by jaivgar** [comment]
Hello,

I was trying to test the new version of the Client-Library, but I was prompted with other exceptions before reaching the part of the code related to this issue:

![Servlet error in version 12](https://user-images.githubusercontent.com/44204948/91840046-583aaa80-ec50-11ea-96f3-836ce22a723d.png)

Now I am not sure how to proceed with this issue, if the problem is unrelated to the core-java-spring I can close it and open a new one in Client-Library repository. What is your opinion?

Regards, Jaime

**Comment by borditamas** [comment]
Hi,

it was related to the new version I have released. Since the Certificate Authority Core System has been migrated new stuffs came into which were mistakenly not added to the client-library related transitive dependencies. 

I've have just deployed the v4.1.3.13 with the fixes and also succesfully run the care demo with it.

Please try it out.

**Comment by jaivgar** [comment]
Hi,

I have just tested again my code with v4.1.3.13 of Client-Library and is works great, no exceptions now.
The bug has been fixed, thanks for your work.

Regards, Jaime
