### ISSUE TITLE
Missing IP address validation

### ISSUE THREAD

**Issue by jenseliasson** [eclipse-arrowhead/core-java-spring#265]
When I was testing during the weekend, I managed to accidentally register the following incomplete IP address "192.168.1." 

When I check the source code, there is no IP address validation performed in the incoming request message.

I think it would be good to make sure that the provider's address is either a valid IP address or a hostname.

**Comment by BlackRose01** [comment]
Maybe you could add a check for 0.0.0.0 here as well. If this should be inserted as address, then all available IP addresses (isUp, isAvailable, noLoopback, noLinkLocal) of the host system should be registered instead of 0.0.0.0.

**Comment by emanuelpalm** [comment]
> Maybe you could add a check for 0.0.0.0 here as well. If this should be inserted as address, then all available IP addresses (isUp, isAvailable, noLoopback, noLinkLocal) of the host system should be registered instead of 0.0.0.0.

I assume you mean that if the IP address is any of the IPv4 or IPv6 wildcard addresses (all zeroes), the service registry should look at the remote host IP address in the TCP connection and use that instead? To me that seems like a valid approach.

**Comment by jenseliasson** [comment]
I think that would be good. We should also not allow the registration of a multicast or broadcast address etc.

**Comment by borditamas** [comment]
bump
