### ISSUE TITLE
Certificate Authority on debian installation - keystore contains 2 key pairs and may try to authenticate itself using the wrong key pair

### ISSUE THREAD

**Issue by mzsilak** [eclipse-arrowhead/core-java-spring#266]
The certificate authority contains its own key pair as well as the cloud certificate key pair. 
In my case the cloudname was "ccpss.fh-burgenland.arrowhead.eu". I noticed that CA was unable to register itself on service registry. Upon further investigation it turned out that CA used the cloud certificate as client certificate. 

The selection is inside the 3rd party library and I found no way to influence it. My workaround was to rename the alias of the cloud certificate. Ultimately I believe that CA needs 2 keystores: One for the keypair of cloud certificate (for signing) and one for its own certificate which behaves like all other systems.

**Comment by tsvetlin** [comment]
@mzsilak Do you have any updates regarding this issue?

**Comment by tsvetlin** [comment]
If you have multiple keys, maybe you can reference them by their alias.

**Comment by mzsilak** [comment]
Hello @tsvetlin ,

I was not working on this issue as I am not too familiar with the certificate authority, but I can look into it.

IMHO, using the alias to reference the certificates does not work for two reasons:
1) The cloud name can be anything and is determined during debian installation. We would need to add the cloud name alias to the application.properties of CA, but then that file could be changed by anybody and it would break the system.
2) I have no possibility to tell the 3rd party library to use a specific alias.

Sorry for my misunderstanding regarding who should look into this issue.

kind regards,
Mario

**Comment by rbocsi** [comment]
Hello @mzsilak,

I think if you can ask all the key pairs from the 3rd party library, then you can decide which is right one, because the cloud certificate's CN has only 4 parts (e.g ccpss.fh-burgenland.arrowhead.eu), while an application's (or core system's) CN has five parts (e.g authorization.ccpss.fh-burgenland.arrowhead.eu).

**Comment by mzsilak** [comment]
Hello,

Its not about getting information from the 3rd party library, its about providing information.
We only have the ability to provide the keystore/truststore and the passwords to the library and the library handles the rest. The issue is that the library chooses the wrong keypair and I don't think its wise to create our own fork of the 3rd party library. 

Thus my suggestion to have a "normal" keystore like all systems have it and a separate "cloud" keystore for certificate signing.
