### ISSUE TITLE
Authorization publickey wrong interface description

### ISSUE THREAD

**Issue by ajoino** [eclipse-arrowhead/core-java-spring#276]
There is a bug in the `/authorization/publickey` API. The interface is currently `HTTP-SECURE-JSON` but it returns a string without quotation marks which can't be read as a JSON string, as [RFC 8259](https://tools.ietf.org/html/rfc8259#section-7) states:
 > A string begins and ends with quotation marks.
 
If this is the intended behavior, the payload interface should be changed to `STRING` or `TEXT`, and if the payload should be `JSON`, the quotation marks should be added.

**Comment by tsvetlin** [comment]
Thank you for pointing out this bug. It will be fixed in the next release (4.4).

**Comment by rbocsi** [comment]
bump

**Comment by MaGaMeGa** [comment]
Resolved by rbocsi at arrowhead-f/core-java-spring branch. Waiting for review and close.
