### ISSUE TITLE
Changing log4j2.xml in the target/ directory does nothing

### ISSUE THREAD

**Issue by jenseliasson** [eclipse-arrowhead/core-java-spring#280]
In order to change the debug levels, the original file in src/main/resources/log4j2.xml must be edited and the software recompiled.

**Comment by rbocsi** [comment]
You can use the log4j2.xml located on a custom path if you tell the program where to find it:

For example:
`java -Dlog4j.configurationFile=file:/path/to/log/log4j2.xml -jar arrowhead-authorization-4.2.0.jar`

**Comment by tsvetlin** [comment]
@jenseliasson  No recompilation is needed. You can define an absolute or relative path where you execute the command from.
