### ISSUE TITLE
Reusing connections in HttpService is hard-coded

### ISSUE THREAD

**Issue by marci543** [eclipse-arrowhead/core-java-spring#283]
`HttpService` forces `HttpClient` to reuse opened connections.
During a testing scenario, I used WireMock to replace some components that are accessed via `HttpService`. These mocks are usually reinitialized between tests.
Reusing connections can cause `NoHttpResponseException` as `HttpClient` tries to use the connection to the older mock to access the reinitialized one.

Possible solutions can be:
- make this configurable
- allow descendant classes to overwrite fields in HttpService
- initialize RestTemplate-related components using Spring which allows overriding

Currently, only reflection-based code can overwrite this configuration.

Lines concerned:
https://github.com/eclipse-arrowhead/core-java-spring/blob/f8498dc2d34cfb6cc70190539059d7264b543b69/core-common/src/main/java/eu/arrowhead/common/http/HttpService.java#L191-L204

**Comment by tsvetlin** [comment]
This is the intended behaviour.

@marci543  Could you please propose a solution on how to make this configurable?

**Comment by marci543** [comment]
I think instead of direct initialization of `HttpClient` and `HttpComponentsClientHttpRequestFactory`, dependency injection could be used.
For the tests I initialize them this way to disable reusing connections:
```java
@Configuration
public class TestHttpClientConfig {
    // reusing connections can cause NoHttpResponseException as the stubs are reinitialized between requests
    // to avoid this disable connection reuse (keep-alive) in HTTP clients
    // https://www.baeldung.com/httpclient-connection-management
    // https://stackoverflow.com/q/55624675
    @Bean
    public HttpClient testHttpClient() {
        return HttpClientBuilder.create()
                .setConnectionReuseStrategy((r, c) -> false)
                .build();
    }

    // https://springframework.guru/using-resttemplate-with-apaches-httpclient/
    // https://github.com/spring-framework-guru/sfg-blog-posts/blob/90e58ca1e539b76d56a5ee98a4812f59b9169cc5/resttemplate/src/main/java/guru/springframework/resttemplate/config/RestTemplateConfig.java
    @Bean
    public HttpComponentsClientHttpRequestFactory clientHttpRequestFactory(HttpClient httpClient) {
        HttpComponentsClientHttpRequestFactory clientHttpRequestFactory = new HttpComponentsClientHttpRequestFactory();
        clientHttpRequestFactory.setHttpClient(httpClient);
        return clientHttpRequestFactory;
    }
}
```

My current workaround (only for test codes) replaces `HttpService` with a descendant that overwrites the `template` variable using reflection. This would be needless if the `createTemplate` and `createClient` methods could be replaced by a subclass, or using dependency injection.
```java
// force AHT to use this class for outgoing REST requests in tests
@Primary
@Component
public class TestHttpService extends HttpService {
    @Autowired
    private ClientHttpRequestFactory httpRequestFactory;

    // replace HttpClient/HttpRequestFactory in base class to make it configurable
    // https://github.com/arrowhead-f/core-java-spring/blob/f8498dc2d34cfb6cc70190539059d7264b543b69/core-common/src/main/java/eu/arrowhead/common/http/HttpService.java#L191-L204
    @PostConstruct
    @Override
    public void init() throws Exception {
        super.init();

        Class<? extends HttpService> cls = HttpService.class;
        Field templateField = cls.getDeclaredField("template");
        templateField.setAccessible(true);
        RestTemplate restTemplate = (RestTemplate) templateField.get(this);
        restTemplate.setRequestFactory(httpRequestFactory);
    }
}
```

**Comment by borditamas** [comment]
In general we don't think that refactoring a working solution beacause of testing is preferable.
And using reflection is an appropiate solution for unit testing.
