### ISSUE TITLE
Docker instructions are contradictory

### ISSUE THREAD

**Issue by Tiegris** [eclipse-arrowhead/core-java-spring#285]
The instructions about Docker setup are contradictory in the main [README.md](https://github.com/eclipse-arrowhead/core-java-spring/blob/b86a70d331a6c283bd45d7c2c0446704056e7dfd/README.md#quickstart_docker) and the [docker/README.md](https://github.com/eclipse-arrowhead/core-java-spring/blob/b86a70d331a6c283bd45d7c2c0446704056e7dfd/docker/README.md). The latter seems outdated.

[docker/README.md](https://github.com/eclipse-arrowhead/core-java-spring/blob/b86a70d331a6c283bd45d7c2c0446704056e7dfd/docker/README.md) file states that:
>You may want to look at, or perhaps even edit, some of those files to get a better understanding of how the Arrowhead Core systems can be configured. **Editing them is not required, however, for the example network to run.**

This seems incorrect, without setting the `domain.name` properties to a proper value, the system will fail to start.
The main [README.md](https://github.com/eclipse-arrowhead/core-java-spring/blob/b86a70d331a6c283bd45d7c2c0446704056e7dfd/README.md#docker-guide) file notes this fact, but this should also be noted in the [docker/README.md](https://github.com/eclipse-arrowhead/core-java-spring/blob/b86a70d331a6c283bd45d7c2c0446704056e7dfd/docker/README.md) file.

SQL initialization is also different in the two files: initSQL.sh vs. create_empty_arrowhead_db.sql

initSQL.sh tries to download a missing file:
https://github.com/eclipse-arrowhead/core-java-spring/blob/b86a70d331a6c283bd45d7c2c0446704056e7dfd/scripts/initSQL.sh#L25

**Comment by tsvetlin** [comment]
Hello!

We are aware of the issue, it is planned to be fixed in April. 

Best wishes,
Svetlin

**Comment by borditamas** [comment]
Hello,

we have just released the v4.6.1, where a more flexible docker approach has been taken and bug fixes were managed.
[Take a look](https://github.com/eclipse-arrowhead/core-java-spring/wiki/Docker) and please open a new issue if you still runs into some error.
