### ISSUE TITLE
application.properties in Docker has wrong server.address

### ISSUE THREAD

**Issue by Tiegris** [eclipse-arrowhead/core-java-spring#286]
With the provided default .properties files some services will fail to start in Docker.
![error](https://user-images.githubusercontent.com/33226948/110929763-9d8b1380-8328-11eb-8353-fb5d2382127b.png)

As we can see the Orchestrator and the Authorization service fails, because the address on line 19 cannot be interpreted.
E.g.:
https://github.com/eclipse-arrowhead/core-java-spring/blob/b86a70d331a6c283bd45d7c2c0446704056e7dfd/docker/core_system_config/orchestrator.properties#L19

After investigating the .properties files of the failing services I found out that those lines have an extra space character at the end of the line.

**Comment by borditamas** [comment]
Hello,

we have just released the v4.6.1, where a more flexible docker approach has been taken and bug fixes were managed.
[Take a look](https://github.com/eclipse-arrowhead/core-java-spring/wiki/Docker) and please open a new issue if you still runs into some error.
