### ISSUE TITLE
Core service registration with custom interface

### ISSUE THREAD

**Issue by rbocsi** [eclipse-arrowhead/core-java-spring#298]
Currently, the ApplicationInitListener registers every core services with HTTP-(IN)SECURE-JSON interface, which is a good default, but sometimes (for example one service in Configuration returns binary data) is not true.

We need to provide a way to specify the interface(s) of a core system service, if it not use the default interface.

**Comment by MaGaMeGa** [comment]
Resolved by rbocsi at arrowhead-f/core-java-spring branch. Waiting for review and close.
