### ISSUE TITLE
Certificate Authority - Possibility to get the certificate authority public key?

### ISSUE THREAD

**Issue by ajoino** [eclipse-arrowhead/core-java-spring#300]
I propose to add a client service to the Certificate Authority system that provides the public key of the certificate authority.

Without the CA public key, it will be impossible to authenticate any incoming certificates in the Python library and TLS will not work.
perhaps something like 'certificateauthority/publickey', similar to the authorization system.

**Comment by tsvetlin** [comment]
Try using Service Registry Query, and query the onboarding service. It has the system information and you can get the public key from there under authenticationInfo.
