### ISSUE TITLE
Network address detection

### ISSUE THREAD

**Issue by borditamas** [eclipse-arrowhead/core-java-spring#309]
In the last AH Tool workshop it was came up that network address detection would be a nice feature when an application system registrates itself, but actually don't know its current ip. Can't really recall, but probably it was mentioned by @emanuelpalm or @jenseliasson.

I've made an [implementation](https://github.com/arrowhead-f/core-java-spring/blob/ip-port-detection/core-common/src/main/java/eu/arrowhead/common/processor/NetworkAddressDetector.java) where we try to detect the address if it's not defined (or invalid), first from the connector itself, but if the request was forwarded by a proxy before the ServiceRegisrty (which is possible to being listed in the config file), then we check the `Forwarded` header(s), and the `X-Forwarded-For` headers(s) after.

Do you (@emanuelpalm, @jenseliasson) or anyone else have any other thoughts on this or suggestions (like another alternative headers we should support)?

**Comment by emanuelpalm** [comment]
Nice!

This is especially relevant if running Arrowhead in insecure mode, or during on-boarding. In those cases, the consuming system won't already have a certificate with subject alternative names that must match its IP address or DNS name. Right?

Proxy header support is good, I guess. :-)

**Comment by borditamas** [comment]
Yeah, in not secured mode we have an easy job, but when the certificates comes into the game, then there some questions arise. 

I think that the address is being not required in the payload is already an adventage from the view of application systems development. It's enough to create the proper certificate for the actual deployment and that's all. 

I can imagine - mostly in the case of experimantal local clouds - that the consumers are operating with `hostname_verification=disabled` and providers without `subject alternative name` in its certs. I would not do that in a real operation, because of the possibility of "man in the middle" attack, but application systems could be developed and tested within such environment (which is much closer to a real one than the insecure mode). At the end only the cert need to be changed and provider could go over to the real environment without any additional programming effort.
