### ISSUE TITLE
Certificate documentation is incorrect

### ISSUE THREAD

**Issue by jenseliasson** [eclipse-arrowhead/core-java-spring#313]
The pdf file for generating client certificates is wrong. The generated example client will not work in a local cloud. 

It would be better to have the documentation create an existing certificate as well, so the reader can compare the newly generated certificate with the one already in the repository.

**Comment by jenseliasson** [comment]
The documentation is still not fixed. Can you send me the word file and I can do it? 
I must anyway add a section for generating .pem certificates for MQTT and other protocols as well as programming languages with no or limited support for PKCS12.

**Comment by borditamas** [comment]
It was fixed, but not merged yet. (It will come with the v4.4.0 release).
See.: https://github.com/arrowhead-f/core-java-spring/tree/development/documentation/certificates
