### ISSUE TITLE
Certificate Authority cannot read keystore CAs without friendly names/aliases

### ISSUE THREAD

**Issue by ajoino** [eclipse-arrowhead/core-java-spring#322]
I'm working on implementing the onboarding procedure for the Python client lib and I'm having an issue with the Certificate authority system (and eventually the System and Device registries). The problem is that the certificates I'm generating do not have a friendly name/alias, which at first I assumed would not be a problem since they are set to the same value in the testcloud1 keystores, but when I start the Certificate authority it gets to [this method](https://github.com/eclipse-arrowhead/core-java-spring/blob/master/core-common/src/main/java/eu/arrowhead/common/Utilities.java#L458)
```java
	public static X509Certificate getRootCertFromKeyStore(final KeyStore keystore) {
		Assert.notNull(keystore, "Key store is not defined.");

		try {
            // debian installation with new certificates have a different alias
			Enumeration<String> enumeration = keystore.aliases();
			while (enumeration.hasMoreElements()) {
				final String alias = enumeration.nextElement();
                final X509Certificate certificate = (X509Certificate) keystore.getCertificate(alias);
                final String commonName = getCertCNFromSubject(certificate.getSubjectDN().getName());
                Assert.notNull(commonName, "Certificate without commonName is not allowed");
                final String[] cnParts = commonName.split("\\.");
				if (cnParts.length == 2 && cnParts[0].equals(AH_MASTER_NAME) && cnParts[1].equals(AH_MASTER_SUFFIX)) {
					return (X509Certificate) keystore.getCertificate(alias);
                }
			}

			final String errorMsg = "Getting the root cert from keystore failed. " +
					"Cannot find alias in the following format: " + AH_MASTER_NAME + "." + AH_MASTER_SUFFIX;
			logger.error(errorMsg);
			throw new ServiceConfigurationError(errorMsg);
        ...
```
and throws the error on the last line there. I think the problem here is the while loop is never executed because I have no aliases in the keystore. Also, the two methods above it, `getCloudCertFromKeyStore` and `getSystemCertFromKeyStore` would probably fail similarly but I assume they just haven't been executed yet.

I find this loop a bit strange. To me, it would make more sense to loop over the certificates directly, if it is possible, and it would work with a wider variety of keystores. Is there a reason this method is implemented the way it is?

**Comment by borditamas** [comment]
As far as I see @kovacskristof was in charge of CA. Please reopen the issue if still relevant.
