### ISSUE TITLE
Orchestrator fails with "Orchestrator can't find authorization check URI."

### ISSUE THREAD

**Issue by emanuelpalm** [eclipse-arrowhead/core-java-spring#328]
I'm using version 4.3.0, as it is included in the `svetlint/orchestrator:4.3.0` docker image.

The following request is issued:
```http
POST /orchestrator/orchestration HTTP/1.1
accept: application/json
content-type: application/json
content-length: 510
host: orchestrator.local:8441
connection: close

{"requesterSystem":{"systemName":"echo_consumer","address":"echo-consumer.local","port":9002,"authenticationInfo":"MIIBIjANBgkq..."}}
```

The `authenticationInfo` field has been truncated for the sake of brevity.

The following response is received:
```http
HTTP/1.1 500
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
Strict-Transport-Security: max-age=31536000 ; includeSubDomains
X-Frame-Options: DENY
Content-Type: application/json
Content-Length: 111
Date: Fri, 16 Jul 2021 18:21:24 GMT
Connection: close

{"errorMessage":"Orchestrator can't find authorization check URI.","errorCode":500,"exceptionType":"ARROWHEAD"}
```

The method responsible for generating the exception in the received response is [here](https://github.com/eclipse-arrowhead/core-java-spring/blob/master/orchestrator/src/main/java/eu/arrowhead/core/orchestrator/service/OrchestratorDriver.java#L339-L351).

Any idea what might be causing this issue?

**Comment by borditamas** [comment]
Hello,

Orchestrator queries the necesarry services at its start up from the ServiceRegistry and saves it into its cache. The provided error happens when, the cache does not contain the necessary service URI.

Please open a new issue if you still facing with such an error with the newer versions.
