### ISSUE TITLE
JSON as EventHandler publish event payload

### ISSUE THREAD

**Issue by jenseliasson** [eclipse-arrowhead/core-java-spring#333]
The payload of an event is currently of type string:
`"payload": "string",`

A very useful improvement would be to allow generic JSON objects to be appended. This gives much greater flexibility for systems to publish readings, alarms etc. compared to using a string,

I, therefore, propose that either payload is changed to a JSON object, or an additional nullable parameter is introduced, e.g.
 ` "json": < generic JSON object or array of objects>`

**Comment by MaGaMeGa** [comment]
I do agree, that in some, maybe even most use cases the payload would be JSON object,
but there may be other use cases where the payload is empty or represented in other format.

As far as I am concerned JSON to String conversion is a straightforward operation.
It could not be always so for the other way around.

However, I would agree that in any production ready implementation, the payload should be strictly defined, and always validated by the subscriber.

To force the constraints on the eventPublish object could be problematic even in a standalone cloud, but as we start to use the events in intercloud scenarios (hopefully in 5.0 version ) the challenge could grow exponential.

I would suggest to define the eventPublish payload validation constraints at the same documentation where the actual event type is defined, and/or enrich the eventType entity with the payload validation constraints.

In that case it would be even possible that a new version of the eventHandler could be started with an optional strategy where the incoming eventPublish objects are validated for the payload - eventType compatibility.

In some use cases the delivery of the events may have strict time constraints, and at those cases the payload validation by the eventHandler may be an unneccessary overhead (those events could be without an actual payload or just token, etc.)

**Comment by jenseliasson** [comment]
Good comments above. I agree.

One solution would be to use optional base64 and add a mine type field. Then any type (string, JSON, XML, binary, ...) can be encoded and the recipients will know how to decode incoming events. On the other hand, Arrowhead is highly based on JSON. 

It would also be good to get more requirements and comments from a broad range of Arrowhead users.
