### ISSUE TITLE
Core services start despite failure to reach service registry

### ISSUE THREAD

**Issue by BlackRose01** [eclipse-arrowhead/core-java-spring#337]
Hello there,

I'm currently trying to implement the Core Service Modules with Docker and I noticed that the modules start successfully despite not reaching the service registry (SR). This is unfortunately very counterproductive as the database (MariaDB) takes a while to start and the SR also takes a while (~180 seconds). Meanwhile the other core services are already started. They show me that the SR is not reachable but do not terminate but just start. I can prevent this with "depends_on" but this does not work with the Java applications.

So my idea would be: Wouldn't it be better to disable the start of the core service if the SR is not reachable. So if the SR is not reachable when starting a core service, the start should be aborted. So it is possible to automate the "automatic reconnection" with the help of the Docker command "restart".

KR,
BlackRose01

**Comment by rbocsi** [comment]
Hello,

Core Services should terminate if any error (such as unreachable Service Registry) occurs during the startup. If a Core Service cannot reach the Service Registry after multiple tries (I think the actual value is 4 with 15 seconds waiting between each try), an exception is thrown, and the shutdown process is started.

However, a thread (started by the Quartz Scheduler, tries to acquire various URIs from the SR) is stucked and prevents the VM to terminate. It is a bug.

We fixed it after your report, it will be the part of the upcoming 4.4.0 release. In the mean time, you can found this (and the whole 4.4.0 release candidate) in the arrowhead-f/core-java-spring repository's development branch.

I don't know much about the docker part, sorry, but I hope this helps you.

**Comment by jerkerdelsing** [comment]
@emanuelpalm This is something you Emanuell should consider in the specs for the bootstrap system.

**Comment by emanuelpalm** [comment]
@jerkerdelsing @rbocsi I think trying 4 times for 15 seconds and then shutting down is a sensible default action. As long as it can be configured to be different.

The device bootstrapper should never shutdown (at least by default), however, as it needs to be possible to use it to start up (or restart) other systems on the same device. I will make sure to leave room for it to be configured, however.

**Comment by jerkerdelsing** [comment]
@emanuelpalm +1
