### ISSUE TITLE
Eventhandler cannot publish event to secure client systems

### ISSUE THREAD

**Issue by ajoino** [eclipse-arrowhead/core-java-spring#341]
Hi.

I'm trying to get the eventhandler to work with the python lib, but the eventhandler cannot publish any events and logs this cryptic error message:
`2021-10-01 14:59:26.139 ERROR bf771247e5f9 --- [pool-2-thread-8] e.a.c.h.HttpService: UnavailableServerException occurred at http://127.0.0.1:5556/event-notifications/93052ef6-fe3d-42cf-bdd4-c4583ec192aa`

This service is available and I can POST JSON to it without issue, but the eventhandler cannot for some reason, and I can't figure it out because the event publication process is basically undocumented (or I haven't found it).

If someone could quickly write down the requirements for the subscriber to receive requests, and give and example EventDTO in JSON format I would be very happy, as I need the eventhandler stuff to work for my Lubeck demo.

**Comment by ajoino** [comment]
While walking home from a disappointing hockey game I started pondering why the event subscriber showed various error codes when a postman request was wrong, but not when the eventhandler tried to publish an event. It then dawned on me that I am in fact using docker and docker networks and of course the eventhandler can't find anything on its own localhost. Once again docker networking bites me in the ass, but that's my fault, not docker's nor the core systems'.

However, I have also found a bug which is not my fault :), which is that the request the eventhandler makes to send events to subscribers is done with `http` even if the subscriber (and by extension the cloud) runs in secure mode, which caught me off guard. I tried the same setup with the same cloud using secure and insecure modes, when running in insecure mode it works but when running in secure mode I get the same error message as in my previous message. I consider this a bug because a secure core system should use TLS for all incoming and outgoing requests it makes, and I think this needs to be fixed asap because this means the eventhandler as is is not production ready, unless I am mistaken somehow.

**Comment by MaGaMeGa** [comment]
Thank you for rising you concern. The Evenhandler can publish events to secure clients. To decide if it publishes to http or https it use the public key (authentication info field) of the subscriber system. If a subscriber has not provided a public key with it's subscription request (aka left the authentication field empty), the Evenhandler will handle it as an unsecured subscriber. Could it be so in you case?
Look [around](https://github.com/eclipse-arrowhead/core-java-spring/blob/master/eventhandler/src/main/java/eu/arrowhead/core/eventhandler/publish/PublishEventTask.java) line 78 
As for documentation, I do agree that there is not much else on Eventhandler than on any other core system : https://github.com/eclipse-arrowhead/core-java-spring/tree/master/documentation/eventhandler, and I do agree that there is room to improve it. I do also think, that the github issues like yours, and all the others ether here or at github.com/arrowhead-f could be a useful extension for the documentation.

**Comment by ajoino** [comment]
Thank you for your answer, I share your sentiment of issues also being documentation, which is one of the reasons I try to use them so whatever I learn is publicly available.

However, I still cannot get the eventhandler to publish to a secure client system. Subscribing with the following payload
```json
{
  "eventType": "test",
  "notifyUri": "/event-notifications/8ee52314-a134-4998-a59b-29702d0cb1ab",
  "subscriberSystem": {
    "systemName": "event_subscriber_1",
    "address": "172.16.1.1",
    "port": 5556,
    "authenticationInfo": "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApMfhEHFdRYX5nD10LDu0qktrH7jbi6kyI0xC0dsJ5kFEd8Eu3kLg+BWMzBZpUEpkCqLLx4eJzZUWnRbaxRHiEPKEzyJvaKsaF/Mhv7TnfL5D/RC71j2QcmLdWNZ9zskaOM6rAXhCNbem571XZ8t6dOL3UP3hGrwqBzNe4+eDyxa0PL445ekPqMMz9kAt1BzZak43TkfopzI3BOBrCbL0ggAl96y9LHAwNEg8kSF0SqemgdoTIMRIIR0IKsGrnpg7Ph2K7HrYlHXIHt2xFaEOAaciFEIoRwAqJBSWztRR3XfuY35siUhMBQtPiKMcfSZpXHCs6ewFi2MJLB9sCvIjUwIDAQAB"
  }
}
```
will not work in secure mode, with the eventhandler logging the same error message as before:
```
2021-10-04 08:29:28.384 ERROR f87b95490576 --- [pool-2-thread-9] e.a.c.h.HttpService: UnavailableServerException occurred at http://172.16.1.1:5556/event-notifications/8ee52314-a134-4998-a59b-29702d0cb1ab
```
Here it claims to be performing an HTTP request and not an HTTPS request, but that might just be an error formatting error. Looking at the eventhandler's subscriptions with `curl -X GET "https://172.16.1.6:8455/eventhandler/mgmt/subscriptions?direction=ASC&sort_field=id" -H "accept: application/json"` (through swagger if that matters) I get the following response:
```json
{
  "data": [
    {
      "id": 2,
      "eventType": {
        "id": 1,
        "eventTypeName": "TEST",
        "createdAt": "2021-10-02 19:44:17",
        "updatedAt": "2021-10-02 19:44:17"
      },
      "subscriberSystem": {
        "id": 7,
        "systemName": "event_subscriber_1",
        "address": "172.16.1.1",
        "port": 5556,
        # No authenticationInfo!?!?!?!
        "createdAt": "2021-10-02 19:50:14",
        "updatedAt": "2021-10-02 19:50:14"
      },
      "filterMetaData": null,
      "notifyUri": "/event-notifications/8ee52314-a134-4998-a59b-29702d0cb1ab",
      "matchMetaData": false,
      "startDate": null,
      "endDate": null,
      "sources": [
        {
          "id": 5,
          "systemName": "event_producer",
          "address": "172.16.1.1",
          "port": 5555,
          "authenticationInfo": "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoOviaLEOwfeP/0OExoawQm1l6TdKfKz0bqD1z0tag5fMJoIpPqbIeq5DSaKfCNUvy3Or2lWs2hY0XU1qwUhOT5tCcAzEet9GSXfvhzgJ0L1AK2hJq2qcmxv4XPLJQU5ZDe3vUgkgw4Q8vAiTikSKqyT5CkDMm9gOwBuhyAWR8JEkozC6K3xMj1f/gWmZi8sg3q0E8uNGaSYehQ8Oosy5asHmojCkmmn4gEN40oGei15TEGTst3fVWW+7dmnvnXmBJSPJfHNDDU7FnDb3SKoUYAHRXc2e1JA9Mzit+Ob3Hw3iuanzlpGVR90a/9lVfza+xSMLA5d9pw4IBO/QASKKIQIDAQAB",
          "createdAt": "2021-10-02 19:44:16",
          "updatedAt": "2021-10-04 06:23:41"
        }
      ],
      "createdAt": "2021-10-04 08:26:02",
      "updatedAt": "2021-10-04 08:26:02"
    }
  ],
  "count": 1
}
```
Here the `authenticationInfo` field of the `subscriberSystem` is missing, which suggests to me that the bug is in the registration process, either that the eventhandler is not saving the data correctly or that I am sending it the wrong information.

No matter what the bug is, I think the way to choose between HTTP and HTTPS is wrong, it shouldn't matter if the subscriber provides the eventhandler with the authentication info or not (it is available in the service or system registries), the only thing that should matter is if the core systems are in secure mode or not.

**Comment by ajoino** [comment]
I checked through the subscription code and got to this line https://github.com/eclipse-arrowhead/core-java-spring/blob/7c280383af4df638841188b48dd3f008ff6487b4/eventhandler/src/main/java/eu/arrowhead/core/eventhandler/database/service/EventHandlerDBService.java#L492 which creates the system that in the end is given to the eventhandler database on line https://github.com/eclipse-arrowhead/core-java-spring/blob/7c280383af4df638841188b48dd3f008ff6487b4/eventhandler/src/main/java/eu/arrowhead/core/eventhandler/service/EventHandlerService.java#L86 (as far as I can tell, I'm not 100% sure this is how it works though.)

Could it be that `systemRepository.findBySystemNameAndAddressAndPort` doesn't return the system with the authentication info?

**Comment by MaGaMeGa** [comment]
You are partially right here: The Eventhandler checks the system in the registry, and use the authinfo field. The subscriber just have to supply the system data to make it identifiable at the registy. So if you registered event_subscriber_1 without authinfo at system registration time, it will not be updated by subscribing to an event. (also no system creation happens at that time)

**Comment by ajoino** [comment]
That would make sense as I registered event_subscriber_1 when running the core systems in insecure mode and only supply it to the eventhandler later. Now I understand what went wrong, thank you.

I do still think that choosing between HTTP and HTTPS should be independent of the subscriber system and only depend on whether the local cloud is secure or not since I cannot see where the authentication info is important here. Is the authentication info important here?
