### ISSUE TITLE
[Documentation] Move, split and update

### ISSUE THREAD

**Issue by BlackRose01** [eclipse-arrowhead/core-java-spring#344]
Hello,

please move the documentation from README.md to the Wiki tab. Currently it is not possible to read the documentation because I don't know if the part which I read is part of the system I want or of another system. Furthermore split the documentation into system related parts. The README.md should only contain a itroduction, how to use the project (compile and start) and a contribution part.

Also update the System registry related part. Currently only onboarding is available but not the query for example.

KR,
BlackRose01

**Comment by jerkerdelsing** [comment]
This is addressed in the v4.4.0 release for which we are awaiting the +1 from PMC. The wiki is not yet used but core system documentation should be in the documentation folder of each core system directory.

**Comment by tsvetlin** [comment]
In progress :)
