### ISSUE TITLE
[Service Registry] Endpoint duplicates?

### ISSUE THREAD

**Issue by BlackRose01** [eclipse-arrowhead/core-java-spring#346]
Hello,

what is the difference between the POST endpoints "/serviceregistry/mgmt" and "/serviceregistry/register"? Both of them take the same payload and returns the same information.

KR,
BlackRose01

**Comment by rbocsi** [comment]
The first one is for the system operator with sysop certificate (like the management tool). System operator can register any system's services.
The second one is for the provider system to register its own services (and only those).

**Comment by BlackRose01** [comment]
Ah, ok. Thank you!
