### ISSUE TITLE
Maven warning about mqttv3.jar dependency

### ISSUE THREAD

**Issue by tsvetlin** [eclipse-arrowhead/core-java-spring#359]
Dear Jens, 

You've added this jar as a dependency, MAVEN issued the following warning as it can be seen on the screenshot.
Please provide a fix for it, referencing this isse.

Thank you in advance!

![image](https://user-images.githubusercontent.com/15650896/141770437-5b739006-fd4c-42bd-b44c-8e5c5fd11385.png)

**Comment by uessrodriguez** [comment]
Hi all

To fix this, for now.

I've simply commented the duplicate dependency on pom file.

Bests
