### ISSUE TITLE
 Failed to collect dependencies at eu.arrowhead:arrowhead-authorization:jar:4.4.0

### ISSUE THREAD

**Issue by uessrodriguez** [eclipse-arrowhead/core-java-spring#360]
Trying maven for docker-all

> mvn clean install -DskipTests

Failed to read artifact descriptor for eu.arrowhead:arrowhead-authorization:jar:4.4.0: Could not transfer artifact eu.arrowhead:arrowhead-authorization:pom:4.4.0 from/to spring-repo (https://repo.spring.io/plugins-release/): Not authorized , ReasonPhrase:Unauthorized.

ReasonPhrase:Unauthorized., Auth is neccesary?

TIA

**Comment by tsvetlin** [comment]
Dear @emanuelpalm,

Could you please check on this issue?

Thank you in advance!

**Comment by emanuelpalm** [comment]
@tsvetlin I'm sorry, but I'm not in a position to spend time on this at the moment. If maintaining the docker-all directory is something you do not wish to spend time on yourselves, I suggest that you delete it.

@uessrodriguez I don't recognize the error message. However, when I wrote the original version of the `docker-all` scripts, the current Arrowhead version was 4.1.3. I guess the error could be related to that.

**Comment by tsvetlin** [comment]
Okay, I'll add this task to the end of my backlog.

**Comment by uessrodriguez** [comment]
Maybe related

https://spring.io/blog/2020/10/29/notice-of-permissions-changes-to-repo-spring-io-fall-and-winter-2020

The problem is not only in docker build is in maven build.

**Comment by tsvetlin** [comment]
Thank you, if you want to pick up the issue in the meantime @uessrodriguez feel free.

**Comment by borditamas** [comment]
Hello,

we have just released the v4.6.1, where a more flexible docker approach has been taken and bug fixes were managed.
[Take a look](https://github.com/eclipse-arrowhead/core-java-spring/wiki/Docker) and please open a new issue if you still runs into some error.
