### ISSUE TITLE
Missing query param in Service Registry documentation

### ISSUE THREAD

**Issue by nicnys-8** [eclipse-arrowhead/core-java-spring#379]
If I'm not mistaken, the _Unregister_ endpoint of the Service Registry requires a _service_uri_ query parameter. That parameter is not mentioned in [the documentation](https://github.com/eclipse-arrowhead/core-java-spring#unregister).

**Comment by borditamas** [comment]
Hello,

documentation has been restructured and moved to the [wiki](https://github.com/eclipse-arrowhead/core-java-spring/wiki/service-unregister)
