### ISSUE TITLE
Number of Connections per user to database

### ISSUE THREAD

**Issue by BlackRose01** [eclipse-arrowhead/core-java-spring#42]
Currently I want to install arrowhead at work for testing purposes but the database I use is restricted and I have to create tickets for changing databases and users. The default connection limit per user is 10 but I see that the service registry use 8 connections on its own. So my question is, what is a reasonable number of connections for the connection limit?

Thank you.

**Comment by tsvetlin** [comment]
Hello!

We will look into the issue.

**Comment by BlackRose01** [comment]
Thank you

**Comment by BlackRose01** [comment]
After a few tests and tickets to the IT I could find out that 50 simultaneous user connections are needed for the system to run without problems and crashes. However, this may increase depending on the request/registration load.
