### ISSUE TITLE
MySQL script contains invalid syntax

### ISSUE THREAD

**Issue by senevoldsen** [eclipse-arrowhead/core-java-spring#422]
Trying to initialize a Docker container with MySQL and the initialization scripts there are errors on the tables from create_arrowhead_tables.sql preventing the database from getting populated.

```console
arrowhead_core_mysql    | 2023-03-10 10:25:27+00:00 [Note] [Entrypoint]: /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/create_empty_arrowhead_db.sql
arrowhead_core_mysql    | ERROR 1067 (42000) at line 1062 in file: 'docker-entrypoint-initdb.d/privileges/create_arrowhead_tables.sql': Invalid default value for 'updated_at'
```
Edit: initSQL.sh does not seem to fetch timemanager_privileges.sql which is required by create_empty_arrowhead.sql.
Edit2: Is it still possible to run a core system with just, service registry, authorization and orchestrator?
Edit3: The gams_privileges.sql tries to assign rights to user gams_knowledge, but it does not appear this user is created anywhere.

**Comment by borditamas** [comment]
Hello,

we have just released the v4.6.1, where a more flexible docker approach has been taken and bug fixes were managed.
[Take a look](https://github.com/eclipse-arrowhead/core-java-spring/wiki/Docker) and please open a new issue if you still runs into some error.
