### ISSUE TITLE
The orchestrator get endpoint, `/orchestrator/mgmt/store` stops working when deleting a provider system that has an orchestrator store entry.

### ISSUE THREAD

**Issue by MrDweller** [eclipse-arrowhead/core-java-spring#450]
# The issue 
If there exists a application system that provides some service, and that provider system has an orchestrator store entry.
If the provider system is deleted before the service or the consumer system, then the orchestrators get endpoint, `/orchestrator/mgmt/store` stops working.
It is still possible to create orchestrator store entries and to use the orchestration-service. But no information about the orchestrator store entries can be received. 

When executing the get  `/orchestrator/mgmt/store` endpoint this is the error,
![image](https://github.com/eclipse-arrowhead/core-java-spring/assets/61691900/343f9ef7-3d64-45d4-a5c2-da6f9d6f2a8e)

The aitia management tool looks like this,
![image](https://github.com/eclipse-arrowhead/core-java-spring/assets/61691900/f3a80a99-392a-47fc-b773-7ce643279d3f)

# Replicate the error

- Create a provider system with one service. 
- Create a consumer system.
- Authorize the consumer system to consume the providers system. 
- Add an orchestrator store entry, between the consumer and provider.
- Delete the provider system via the `/serviceregistry/unregister-system` endpoint.

**Comment by borditamas** [comment]
Many thanks for reporting the issue, I can confirm its existance.

Unfortunatelly the main problem is coming from a design flaw, which is already addressed in version 5.0 specifications and could be fully resolved only with that release.

In the mean time, I have made a workaround which also solves the issue and will be released in v4.6.2 (planned for early February).

At the moment you have two options:

- delete the related store enrtries (where the unregistered system is referred as provider)
- you can build a new executable jar of Orchestrator by your own from the `development` branch ([wiki hint](https://github.com/eclipse-arrowhead/core-java-spring/wiki/Compile-Only-One-Module))

**Comment by borditamas** [comment]
v4.6.2 has been released
