### ISSUE TITLE
Debian package generation

### ISSUE THREAD

**Issue by tsvetlin** [eclipse-arrowhead/core-java-spring#54]
Debian package generation, similar to core-java.

**Comment by rbocsi** [comment]
I am already working on it on the deb-installers branch. In the meantime, you can use the Compile source code and manually install MySQL and Maven. from our Quick Start Guide.

**Comment by tsvetlin** [comment]
Debian packages are ready, install guide: https://github.com/arrowhead-f/core-java-spring#quickstart_debian
