### ISSUE TITLE
on start: BadPayloadException: orchestrator is a reserved arrowhead core system name

### ISSUE THREAD

**Issue by BlackRose01** [eclipse-arrowhead/core-java-spring#59]
Hello there,

when I want to start the project then I get the error message in the orchestrator module (as BadPayloadException) from the service registry that the name "orchestrator" is a reserved arrowhead core system name

BlackRose01

**Comment by borditamas** [comment]
Hello,

thanks for your note. Bug is already fixed on development branch and will be merged soon to the master.

Br, Tamás

**Comment by tsvetlin** [comment]
Hello! 
It's in master now. Please try it out and if it's fixed please close the issue.

**Comment by BlackRose01** [comment]
It's tested and the problem is solved. Thank you!
