### ISSUE TITLE
Swagger title and grouping

### ISSUE THREAD

**Issue by tsvetlin** [eclipse-arrowhead/core-java-spring#63]
Each core systems swagger page should have a proper title and grouping.

Example picture shows Service Registry, but it's applicable for all other core systems as well.
![Screenshot 2019-09-15 at 13 58 49](https://user-images.githubusercontent.com/15650896/64921308-0dffb580-d7c2-11e9-9b30-a09d000ef2cc.png)
![Screenshot 2019-09-15 at 14 05 21](https://user-images.githubusercontent.com/15650896/64921309-0dffb580-d7c2-11e9-9837-83c1d562e6c2.png)

**Comment by rbocsi** [comment]
Done. See in development branch

**Comment by tsvetlin** [comment]
Please remove the Arrowhead word. Title should only be the name of the core system.

Thank you.
![Screenshot 2019-09-17 at 12 34 11](https://user-images.githubusercontent.com/15650896/65034582-9eb3ce00-d947-11e9-8761-06c1d4e71ecd.png)

**Comment by tsvetlin** [comment]
It's now ready.
