### ISSUE TITLE
Missing documentation on how to start insecure core systems

### ISSUE THREAD

**Issue by cochicde** [eclipse-arrowhead/core-java-spring#78]
Before there was the possibility to pass a flag to the .jar file to start secure or insecure. Now I'm not finding it. The only way I found is to change the code in 

resources/application.properties -> server.ssl.enabled=false

in each core system and then recompile. But then, the Gatekeeper tests fail

**Comment by rbocsi** [comment]
Hi,

To start in insecure mode, you have to change the property you have already found. However, you don't have change in the resources folder. In each target folder there is an application.properties file besides the jar file. You can change that and you can start the systems without recompile. (But, please note if you recompile after the changes, the application.properties in the target folders will be overwritten by the default ones in the resources folder).

In the new version, the Gatekeeper and Gateway are used encryption based on the certificates, hence there is no way to start Gatekeeper and Gateway in insecure mode. But you can use the local cloud without these core systems. All you have to do to set gatekeeper_is_present=false in the application.properties of the ochestrator, open the starting script (start_coresystems.bat or start_coresystems.sh depends on operation system) and comment out the lines that starts these core systems.

Hope it helps.

As for the documentations:  it is a work in progress.
