### ISSUE TITLE
Secure server certificates

### ISSUE THREAD

**Issue by Towfiqomi** [eclipse-arrowhead/core-java-spring#79]
Hi,

In the secure mode, the browser asks for a certificate to authenticate to https://127.0.0.1:8443/api.

I could not get it working, any suggestions.

**Comment by borditamas** [comment]
Hello,

you should import the sysop certificate located in core-java-spring\serviceregistry\src\main\resources\certificates. This is a system operator certificate example which required for interacting with the core systems in secure mode.

**Comment by borditamas** [comment]
Another thing  that there is no "/api" path in v4.1.3. You can simply check  https://127.0.0.1:8443 and will be redirected to https://127.0.0.1:8443/swagger-ui.html#/ where the api documentations are.

**Comment by Towfiqomi** [comment]
Thank you for the help and great work guys on the new version.
