### ISSUE TITLE
MySQL script error on Mac

### ISSUE THREAD

**Issue by vanDeventer** [eclipse-arrowhead/core-java-spring#86]
Hello,

I got an error when running the create_empty_arrowhead_db script. See attached screenshot.
<img width="1680" alt="Screenshot 2019-10-06 at 12 21 13" src="https://user-images.githubusercontent.com/22440951/66267683-6b70aa80-e834-11e9-902e-039b2acf8784.png">

**Comment by tsvetlin** [comment]
Hello!

Thanks for your feedback, I can confirm it, it will be fixed shortly.

Best wishes,
Svetlin

**Comment by tsvetlin** [comment]
Hello!

It's fixed by [https://github.com/arrowhead-f/core-java-spring/commit/244d32141c04933830bd4fd78b443b4cf540dd41](https://github.com/arrowhead-f/core-java-spring/commit/244d32141c04933830bd4fd78b443b4cf540dd41).

The changes are in `master` branch.
