### ISSUE TITLE
unable to access DEBIAN_INSTALL.md and DEBIAN_DEV.md files of version 4.1.2 

### ISSUE THREAD

**Issue by sumi0910** [eclipse-arrowhead/core-java-spring#87]
Whenever trying to access these files, error 404 found and also no instructions provided to install 4.1.3 on Debian based Linux distribution.

**Comment by tsvetlin** [comment]
Hello!

They are not yet available: We already have an issue [https://github.com/arrowhead-f/core-java-spring/issues/54](https://github.com/arrowhead-f/core-java-spring/issues/54) for that, closing this as a duplicate. 

If you would like to help us out with that, feel free.

Kind regards,
Svetlin
