### ISSUE TITLE
Tried Installing v4.1.2 but during execution of mvn install command, v4.1.3 snapshot is created

### ISSUE THREAD

**Issue by sumi0910** [eclipse-arrowhead/core-java-spring#92]
Are we supposed to work on 4.1.3 or can we go ahead with 4.1.2 because my application is completely based on C++ and v4.1.3 is great to work if someone wants to build their application in java but not in c+ +.

**Comment by tsvetlin** [comment]
Hello.

You can use the [core-java](https://github.com/arrowhead-f/core-java) repository for your project. We will create a c++ library for it in the future.
Use this release: [https://github.com/arrowhead-f/core-java/releases/tag/4.1.2](https://github.com/arrowhead-f/core-java/releases/tag/4.1.2)

**Comment by sumi0910** [comment]
You can close the issue
